ALTER TABLE EON_USERS ADD (USER_ID_OLD  NUMBER(9));     
ALTER TABLE EON_USER_DEALING_PATTERN ADD (USER_DEALING_PATTERN_ID_OLD  NUMBER(9));
ALTER TABLE EON_ADMIN_MEMBER
 ADD (ADMIN_MEMBER_ID_OLD  NUMBER);
ALTER TABLE EON_SKU_GROUP
 ADD (SKU_GROUP_ID_OLD  NUMBER(9));
ALTER TABLE EON_SORT_SKU_GROUP
ADD PRIMARY KEY (USER_ID, SKU_GROUP_ID);
ALTER TABLE EON_SORT_SKU_GROUP
 ADD (USER_ID_OLD  NUMBER(9));
ALTER TABLE EON_SORT_SKU_GROUP
 ADD (SKU_GROUP_ID_OLD  NUMBER(9));
ALTER TABLE EON_ORDER
 ADD (ORDER_ID_OLD  NUMBER(9));
ALTER TABLE EON_ORDER_ITEM
 ADD (ORDER_ITEM_ID_OLD  NUMBER(9));
ALTER TABLE EON_SKU
 ADD (SKU_ID_OLD  NUMBER(9));
ALTER TABLE EON_SKU
 ADD (ORIGINAL_SKU_ID_OLD  NUMBER(9));
ALTER TABLE EON_COMMENTS_INBOX
 ADD (COMMENTS_INBOX_ID_OLD  NUMBER(9));
ALTER TABLE EON_ORDER_ALLOCATION
 ADD (ORDER_ALLOCATION_ID_OLD  NUMBER(9));
ALTER TABLE EON_ORDER_RECEIVED
 ADD (ORDER_RECEIVED_ID_OLD  NUMBER(9));
ALTER TABLE EON_ORDER_BILLING
 ADD (ORDER_BILLING_ID_OLD  NUMBER(9));  

