--Add UNIQUE CONSTRAINT for table EON_COMPANY columns COMPANY_NAME
ALTER TABLE EON_COMPANY ADD (
  CONSTRAINT EON_COMPANY_UK1
 UNIQUE (COMPANY_NAME)USING INDEX TABLESPACE EON_INDX01);

--Add UNIQUE CONSTRAINT for table EON_COMPANY columns SHORT_NAME
ALTER TABLE EON_COMPANY ADD (
  CONSTRAINT EON_COMPANY_UK2
 UNIQUE (SHORT_NAME)USING INDEX TABLESPACE EON_INDX01);

CREATE TABLE EON_SHOW_HIDE_COLUMN
(
  USER_ID               NUMBER(9)		NOT NULL,
  COMPANY_NAME			CHAR(1 BYTE)	DEFAULT '1',
  SELLER_NAME			CHAR(1 BYTE)	DEFAULT '1',
  GROUP_NAME			CHAR(1 BYTE)	DEFAULT '1',
  MARKET_CONDITION		CHAR(1 BYTE)	DEFAULT '1',
  SKU_NAME				CHAR(1 BYTE)	DEFAULT '1',
  AREA_PRODUCTION		CHAR(1 BYTE)	DEFAULT '1',
  CLASS_1				CHAR(1 BYTE)	DEFAULT '1',
  CLASS_2				CHAR(1 BYTE)	DEFAULT '1',
  PRICE_1				CHAR(1 BYTE)	DEFAULT '1',
  PRICE_2				CHAR(1 BYTE)	DEFAULT '1',
  PRICE_WO_TAX			CHAR(1 BYTE)	DEFAULT '1',
  PRICE_W_TAX			CHAR(1 BYTE)	DEFAULT '1',
  PIECE_PRICE			CHAR(1 BYTE)	DEFAULT '1',
  SELLING_PRICE			CHAR(1 BYTE)	DEFAULT '1',
  GROSS_PROFIT_RATE		CHAR(1 BYTE)	DEFAULT '1',
  SELLING_UOM			CHAR(1 BYTE)	DEFAULT '1',
  PACKAGE_QUANTITY		CHAR(1 BYTE)	DEFAULT '1',
  PACKAGE_TYPE			CHAR(1 BYTE)	DEFAULT '1',
  UOM					CHAR(1 BYTE)	DEFAULT '1',
  SKU_COMMENT			CHAR(1 BYTE)	DEFAULT '1',
  SKU_MAX_LIMIT			CHAR(1 BYTE)	DEFAULT '1',
  ROW_QTY				CHAR(1 BYTE)	DEFAULT '1'
)
TABLESPACE EON_DATA1 LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE EON_SHOW_HIDE_COLUMN ADD (
  CONSTRAINT EON_SHOW_HIDE_COLUMN_PK
 PRIMARY KEY 
 (USER_ID)USING INDEX TABLESPACE EON_INDX01);
 
CREATE SEQUENCE EON_SKU_BA_ID_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;
 
CREATE TABLE EON_SELLING_UOM
(
  ID_SELLING_UOM	NUMBER(9)		NOT NULL,
  CATEGORY_ID		NUMBER(9),
  SELLING_UOM_NAME	VARCHAR2 (15 Char)
)
TABLESPACE EON_DATA1 LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE EON_SELLING_UOM ADD (
  CONSTRAINT EON_SELLING_UOM_PK
 PRIMARY KEY 
 (ID_SELLING_UOM)USING INDEX TABLESPACE EON_INDX01);

--Create initial data for Selling UOM look up
Insert into EON_SELLING_UOM
   (SELLING_UOM_ID, CATEGORY_ID, SELLING_UOM_NAME)
 Values
   (EON_SELLING_UOM_SEQ.NEXTVAL, 1, '�s�[�X');
Insert into EON_SELLING_UOM
   (SELLING_UOM_ID, CATEGORY_ID, SELLING_UOM_NAME)
 Values
   (EON_SELLING_UOM_SEQ.NEXTVAL, 1, 'C/S');
Insert into EON_SELLING_UOM
   (SELLING_UOM_ID, CATEGORY_ID, SELLING_UOM_NAME)
 Values
   (EON_SELLING_UOM_SEQ.NEXTVAL, 2, '�s�[�X');
Insert into EON_SELLING_UOM
   (SELLING_UOM_ID, CATEGORY_ID, SELLING_UOM_NAME)
 Values
   (EON_SELLING_UOM_SEQ.NEXTVAL, 2, 'C/S');
Insert into EON_SELLING_UOM
   (SELLING_UOM_ID, CATEGORY_ID, SELLING_UOM_NAME)
 Values
   (EON_SELLING_UOM_SEQ.NEXTVAL, 3, '�s�[�X');
Insert into EON_SELLING_UOM
   (SELLING_UOM_ID, CATEGORY_ID, SELLING_UOM_NAME)
 Values
   (EON_SELLING_UOM_SEQ.NEXTVAL, 3, 'KG');
 
CREATE TABLE EON_SKU_BA
(
  SKU_BA_ID			NUMBER(9)		NOT NULL,
  PIECE_PRICE		NUMBER(9),
  SELLING_PRICE		NUMBER(9),
  FK_ID_SELLING_UOM	NUMBER(9),
  SKU_COMMENT		VARCHAR2(50 Char)
)
TABLESPACE EON_DATA1 LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE EON_SKU_BA ADD (
  CONSTRAINT EON_SKU_BA_PK
 PRIMARY KEY 
 (SKU_BA_ID)USING INDEX TABLESPACE EON_INDX01);

ALTER TABLE EON_SKU_BA ADD (
  CONSTRAINT EON_SKU_BA_FK
 FOREIGN KEY (FK_ID_SELLING_UOM) 
 REFERENCES EON_SELLING_UOM (ID_SELLING_UOM));

ALTER TABLE EON_ORDER_ITEM 
  ADD SKU_BA_ID NUMBER(9);

ALTER TABLE EON_ORDER_ITEM ADD (
  CONSTRAINT EON_ORDER_ITEM_FK5
 FOREIGN KEY (SKU_BA_ID) 
 REFERENCES EON_SKU_BA (SKU_BA_ID));

ALTER TABLE EON_ORDER_ALLOCATION 
  ADD SKU_BA_ID NUMBER(9);

ALTER TABLE EON_ORDER_ALLOCATION ADD (
  CONSTRAINT EON_ORDER_ALLOCATION_FK5
 FOREIGN KEY (SKU_BA_ID) 
 REFERENCES EON_SKU_BA (SKU_BA_ID));

ALTER TABLE EON_ORDER_RECEIVED 
  ADD SKU_BA_ID NUMBER(9);

ALTER TABLE EON_ORDER_RECEIVED ADD (
  CONSTRAINT EON_ORDER_RECEIVED_FK5
 FOREIGN KEY (SKU_BA_ID) 
 REFERENCES EON_SKU_BA (SKU_BA_ID));
 
ALTER TABLE EON_ORDER_BILLING 
  ADD SKU_BA_ID NUMBER(9);

ALTER TABLE EON_ORDER_BILLING ADD (
  CONSTRAINT EON_ORDER_BILLING_FK5
 FOREIGN KEY (SKU_BA_ID) 
 REFERENCES EON_SKU_BA (SKU_BA_ID));
 
 
COMMIT;