DROP SEQUENCE EON_SKU_CATEGORY_SEQ;

CREATE SEQUENCE EON_SKU_CATEGORY_SEQ
  START WITH 4
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  ORDER;

-- Additional Meat Category
INSERT INTO EON_CATEGORY (SKU_CATEGORY_ID, DESCRIPTION, TAB_NAME) VALUES (EON_SKU_CATEGORY_SEQ.nextval, 'Meat', 'Meat');
INSERT INTO EON_ORDER_UNIT (ORDER_UNIT_ID, CATEGORY_ID, ORDER_UNIT_NAME) VALUES (EON_ORDER_UNIT_SEQ.NEXTVAL, EON_SKU_CATEGORY_SEQ.currval, 'ピース');
INSERT INTO EON_ORDER_UNIT (ORDER_UNIT_ID, CATEGORY_ID, ORDER_UNIT_NAME) VALUES (EON_ORDER_UNIT_SEQ.NEXTVAL, EON_SKU_CATEGORY_SEQ.currval, 'KG');
INSERT INTO EON_SELLING_UOM (ID_SELLING_UOM, CATEGORY_ID, SELLING_UOM_NAME) VALUES (EON_SELLING_UOM_SEQ.NEXTVAL, EON_SKU_CATEGORY_SEQ.currval, 'ピース');
INSERT INTO EON_SELLING_UOM (ID_SELLING_UOM, CATEGORY_ID, SELLING_UOM_NAME) VALUES (EON_SELLING_UOM_SEQ.NEXTVAL, EON_SKU_CATEGORY_SEQ.currval, 'KG');

-- Additional Meat Category
INSERT INTO EON_CATEGORY (SKU_CATEGORY_ID, DESCRIPTION, TAB_NAME) VALUES (EON_SKU_CATEGORY_SEQ.nextval, 'Delica', 'Delica');
INSERT INTO EON_ORDER_UNIT (ORDER_UNIT_ID, CATEGORY_ID, ORDER_UNIT_NAME) VALUES (EON_ORDER_UNIT_SEQ.NEXTVAL, EON_SKU_CATEGORY_SEQ.currval, 'ピース');
INSERT INTO EON_ORDER_UNIT (ORDER_UNIT_ID, CATEGORY_ID, ORDER_UNIT_NAME) VALUES (EON_ORDER_UNIT_SEQ.NEXTVAL, EON_SKU_CATEGORY_SEQ.currval, 'KG');
INSERT INTO EON_SELLING_UOM (ID_SELLING_UOM, CATEGORY_ID, SELLING_UOM_NAME) VALUES (EON_SELLING_UOM_SEQ.NEXTVAL, EON_SKU_CATEGORY_SEQ.currval, 'ピース');
INSERT INTO EON_SELLING_UOM (ID_SELLING_UOM, CATEGORY_ID, SELLING_UOM_NAME) VALUES (EON_SELLING_UOM_SEQ.NEXTVAL, EON_SKU_CATEGORY_SEQ.currval, 'KG');

COMMIT;