--Add DISPLAY_ALLOC_QTY in EON_USER_PREF_FLAGS
ALTER TABLE EON_USER_PREF_FLAGS ADD (DISPLAY_ALLOC_QTY  CHAR(1 BYTE) DEFAULT 0);

--Add LAST_RUN_DATE for Auto Download Schedule
ALTER TABLE EON_AUTODWNLD_SCHEDULE ADD (LAST_RUN_DATE  TIMESTAMP(6));

--Performance
CREATE INDEX EON_ORDER_ITEM_INDEX1 ON EON_ORDER_ITEM (SKU_ID);

--Add UNFINALIZE_RECEIVED in EON_USER_PREF_FLAGS
ALTER TABLE EON_USER_PREF_FLAGS ADD (UNFINALIZE_RECEIVED  CHAR(1 BYTE) DEFAULT 0);

COMMIT;