CREATE TABLE EON_TERMS_OF_SERVICE 
(
  ID VARCHAR(32) NOT NULL 
, VERSION NUMBER DEFAULT 1 NOT NULL  
, CONTENT CLOB NOT NULL 
, EMAILLIST VARCHAR2(300) NOT NULL 
, CREATEDDATE TIMESTAMP(6) NOT NULL 
, CREATEDBY VARCHAR2(32 CHAR) NOT NULL
, MODIFIEDDATE TIMESTAMP(6) 
, MODIFIEDBY VARCHAR2(32 CHAR)
, CONSTRAINT EON_TERMS_OF_SERVICE_PK PRIMARY KEY (ID)
  ,CONSTRAINT "EON_TERMS_OF_SERVICE_EON__FK1" FOREIGN KEY ("CREATEDBY")
	  REFERENCES "EON01"."EON_USERS" ("USERNAME") 
)
TABLESPACE EON_DATA1 LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

