insert into migration_user(batch_number,username,password,company_name) values (501, 'fsmatsuasaa', '55ctva', '㈱フレッシュシステム(青海)G1');
insert into migration_user(batch_number,username,password,company_name) values (501, 'fssadamatsua', 'fuesi3', '㈱フレッシュシステム(青海)G1');
insert into migration_user(batch_number,username,password,company_name) values (501, 'fskawaguchia', 'mvr66y', '㈱フレッシュシステム(青海)G1');
insert into migration_user(batch_number,username,password,company_name) values (501, 'fsnagatsukaa', 'vtd564', '㈱フレッシュシステム(青海)G1');
insert into migration_user(batch_number,username,password,company_name) values (501, 'fsbejikkusua', 'hp954n', '㈱フレッシュシステム(青海)G1');
insert into migration_user(batch_number,username,password,company_name) values (501, 'fsootaatofu', 'k454ff', '㈱フレッシュシステム(青海)G1');
insert into migration_user(batch_number,username,password,company_name) values (501, 'fstokyofasa2', 'yi4xuv', '㈱フレッシュシステム(青海)G1');
insert into migration_user(batch_number,username,password,company_name) values (501, 'fssgnyavegi', '5gs4ea', '㈱フレッシュシステム(青海)G1');
insert into migration_user(batch_number,username,password,company_name) values (501, 'fsyaoyoshiatowa', 'm1uyvn', '㈱フレッシュシステム(青海)G1');
insert into migration_user(batch_number,username,password,company_name) values (501, 'fstouwaca', '5g4o74', '㈱フレッシュシステム(青海)G1');
insert into migration_user(batch_number,username,password,company_name) values (501, 'fsaveayoko', 'o1vrwl', '㈱フレッシュシステム(青海)G1');
insert into migration_user(batch_number,username,password,company_name) values (501, 'fssimamuraa', 'gcmo26', '㈱フレッシュシステム(青海)G1');
insert into migration_user(batch_number,username,password,company_name) values (501, 'fssimamuraa2', 'gcmo26', '㈱フレッシュシステム(青海)G1');
insert into migration_user(batch_number,username,password,company_name) values (501, 'fszennoyamatoa', 'gcmo26', '㈱フレッシュシステム(青海)G1');
insert into migration_user(batch_number,username,password,company_name) values (501, 'fssevenataka', 'oos50k', '㈱フレッシュシステム(青海)G1');
insert into migration_user(batch_number,username,password,company_name) values (501, 'fsleoa', 'p3a6uj', '㈱フレッシュシステム(青海)G1');
insert into migration_user(batch_number,username,password,company_name) values (501, 'fsleoa2', 'p3a6uj', '㈱フレッシュシステム(青海)G1');
insert into migration_user(batch_number,username,password,company_name) values (501, 'fsnumadua', '6jdtps', '㈱フレッシュシステム(青海)G1');
insert into migration_user(batch_number,username,password,company_name) values (501, 'matsuasa', '88kcpj', '株式会社松浅');
insert into migration_user(batch_number,username,password,company_name) values (501, 'sadamatsu', 'qfq8dv', '株式会社築地定松');
insert into migration_user(batch_number,username,password,company_name) values (501, 'kawaguchi', '85vdaq', '長塚青果');
insert into migration_user(batch_number,username,password,company_name) values (501, 'nagatsuka', '4gxt33', '長塚青果');
insert into migration_user(batch_number,username,password,company_name) values (501, 'vegi', 'u559au', 'ベジックス');
insert into migration_user(batch_number,username,password,company_name) values (501, 'tokyof', 'ncoc33', 'TOKYOフレッシュ株式会社昭島支店');
insert into migration_user(batch_number,username,password,company_name) values (501, 'shigenoya', '38d7pd', 'ベジックス');
insert into migration_user(batch_number,username,password,company_name) values (501, 'yaoitab', 'bxz93g', '有限会社　八百義');
insert into migration_user(batch_number,username,password,company_name) values (501, 'yaokum', 'c2jdrz', '有限会社　八百義');
insert into migration_user(batch_number,username,password,company_name) values (501, 'yaooya', '9k8w1d', '有限会社　八百義');
insert into migration_user(batch_number,username,password,company_name) values (501, 'yaoura', '0nh0v5', '有限会社　八百義');
insert into migration_user(batch_number,username,password,company_name) values (501, 'yaofer', 'ltxa8f', '有限会社　八百義');
insert into migration_user(batch_number,username,password,company_name) values (501, 'yaomar', '7mj99u', '有限会社　八百義');
insert into migration_user(batch_number,username,password,company_name) values (501, 'yaomet', '8czs7o', '有限会社　八百義');
insert into migration_user(batch_number,username,password,company_name) values (501, 'yaokog', 'qv1lot', '有限会社　八百義');
insert into migration_user(batch_number,username,password,company_name) values (501, 'yaonis', 'm5dhfg', '有限会社　八百義');
insert into migration_user(batch_number,username,password,company_name) values (501, 'touwac', 'cps7az', '株式会社東和農産　千葉');
insert into migration_user(batch_number,username,password,company_name) values (501, 'yokosukab', 'xnn4cc', '横須賀青果物株式会社');
insert into migration_user(batch_number,username,password,company_name) values (501, 'snaga', 't986g9', '株式会社しまむら');
insert into migration_user(batch_number,username,password,company_name) values (501, 'snaka', 'a2uf68', '株式会社しまむら');
insert into migration_user(batch_number,username,password,company_name) values (501, 'sekimae', 'r2rxi9', '株式会社しまむら');
insert into migration_user(batch_number,username,password,company_name) values (501, 'soogami', '36b8ct', '株式会社しまむら');
insert into migration_user(batch_number,username,password,company_name) values (501, 'stamura', 'mpm37k', '株式会社しまむら');
insert into migration_user(batch_number,username,password,company_name) values (501, 'sooiso', 'v57zjd', '株式会社しまむら');
insert into migration_user(batch_number,username,password,company_name) values (501, 'sasahi', 'c496f9', '株式会社しまむら');
insert into migration_user(batch_number,username,password,company_name) values (501, 'snakaha', '48433z', '株式会社しまむら');
insert into migration_user(batch_number,username,password,company_name) values (501, 'ssumire', 'm333z3', '株式会社しまむら');
insert into migration_user(batch_number,username,password,company_name) values (501, 'stokunobu', 'p5zi59', '株式会社しまむら');
insert into migration_user(batch_number,username,password,company_name) values (501, 'skaname', '37eg3w', '株式会社しまむら');
insert into migration_user(batch_number,username,password,company_name) values (501, 'stachibana', 'rmr6nn', '株式会社しまむら');
insert into migration_user(batch_number,username,password,company_name) values (501, 'zyamato', '37eg3w', 'JA全農青果センター株式会社');
insert into migration_user(batch_number,username,password,company_name) values (501, 'seven', 'hlrbi4', 'セブンイレブン');
insert into migration_user(batch_number,username,password,company_name) values (501, 'leohonda', 'x74k47', '宍倉');
insert into migration_user(batch_number,username,password,company_name) values (501, 'leomisaki', 'ziz0p6', '宍倉');
insert into migration_user(batch_number,username,password,company_name) values (501, 'numaducs', '4dxqve', '沼津中央青果');
insert into migration_user(batch_number,username,password,company_name) values (501, 'nagatsukakanri', 'n2392s', '長塚青果');
insert into migration_user(batch_number,username,password,company_name) values (501, 'vegikanri', 'mh7i6k', 'ベジックス');
insert into migration_user(batch_number,username,password,company_name) values (501, 'yaoyoshi', 'wq33c3', '有限会社　八百義');
insert into migration_user(batch_number,username,password,company_name) values (501, 'smmrb', '47yaai', '株式会社しまむら');
