CREATE TABLESPACE EON_DATA1 DATAFILE 
  'C:\ORACLE\PRODUCT\10.2.0\ORADATA\TESTDB\EON_DATA1_01.DBF' SIZE 7680K AUTOEXTEND ON NEXT 1280K MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TABLESPACE EON_INDX01 DATAFILE 
  'C:\ORACLE\PRODUCT\10.2.0\ORADATA\TESTDB\EON_INDX01.DBF' SIZE 7680K AUTOEXTEND ON NEXT 1280K MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


