ALTER TABLE EON_SORT_COMPANY_BUYERS ADD (
  CONSTRAINT EON_SORT_COMPANY_BUYERS_PK
 PRIMARY KEY
 (USER_ID, COMPANY_ID)USING INDEX TABLESPACE EON_INDX01);

ALTER TABLE EON_ADMIN_MEMBER ADD (
  CONSTRAINT EON_ADMIN_MEMBER_PK
 PRIMARY KEY
 (ADMIN_MEMBER_ID)USING INDEX TABLESPACE EON_INDX01);

ALTER TABLE EON_AKADEN_SKU ADD (
  CONSTRAINT EON_AKADEN_SKU_PK
 PRIMARY KEY
 (AKADEN_SKU_ID)USING INDEX TABLESPACE EON_INDX01);

ALTER TABLE EON_CATEGORY ADD (
  CONSTRAINT EON_SKU_CATEGORY_PK
 PRIMARY KEY
 (SKU_CATEGORY_ID)USING INDEX TABLESPACE EON_INDX01);

ALTER TABLE EON_COMMENTS_INBOX ADD (
  CONSTRAINT EON_COMMENTS_INBOX_PK
 PRIMARY KEY
 (COMMENTS_INBOX_ID)USING INDEX TABLESPACE EON_INDX01);

ALTER TABLE EON_COMMENTS_OUTBOX ADD (
  CONSTRAINT EON_COMMENTS_OUTBOX_PK
 PRIMARY KEY
 (COMMENTS_OUTBOX_ID)USING INDEX TABLESPACE EON_INDX01);

ALTER TABLE EON_COMPANY ADD (
  CONSTRAINT EON_COMPANY_PK
 PRIMARY KEY
 (COMPANY_ID)USING INDEX TABLESPACE EON_INDX01);

ALTER TABLE EON_COMPANY_TYPE ADD (
  CONSTRAINT EON_COMPANY_TYPE_PK
 PRIMARY KEY
 (COMPANY_TYPE_ID)USING INDEX TABLESPACE EON_INDX01);
 
ALTER TABLE EON_COMPANY_DEALING_PATTERN ADD (
  CONSTRAINT EON_COMPANY_DEALING_PATTERN_PK
 PRIMARY KEY
 (COMPANY_DEALING_PATTERN_ID),
  CONSTRAINT COMPANY_DEALING_PATTERN_UK1
 UNIQUE (COMPANY_01, COMPANY_02, DEALING_PATTERN_RELATION_ID)USING INDEX TABLESPACE EON_INDX01);
 
ALTER TABLE EON_DEALING_PATTERN_RELATION ADD (
  CONSTRAINT EON_DEALING_PATTERNRELATION_PK
 PRIMARY KEY
 (DEALING_PATTERN_RELATION_ID)USING INDEX TABLESPACE EON_INDX01);

ALTER TABLE EON_LOGIN_INQUIRY_REQUEST ADD (
  CONSTRAINT EON_LOGIN_INQUIRY_REQUEST_PK
 PRIMARY KEY
 (INQUIRY_REQUEST_ID)USING INDEX TABLESPACE EON_INDX01);

ALTER TABLE EON_ORDER ADD (
  CONSTRAINT EON_ORDER_PK
 PRIMARY KEY
 (ORDER_ID),
  CONSTRAINT EON_ORDER_UK1
 UNIQUE (SELLER_ID, BUYER_ID, DELIVERY_DATE)USING INDEX TABLESPACE EON_INDX01);

ALTER TABLE EON_ORDER_AKADEN ADD (
  CONSTRAINT EON_ORDER_AKADEN_PK
 PRIMARY KEY
 (ORDER_AKADEN_ID)USING INDEX TABLESPACE EON_INDX01);

ALTER TABLE EON_ORDER_ALLOCATION ADD (
  CONSTRAINT EON_ORDER_ALLOCATION_PK
 PRIMARY KEY
 (ORDER_ALLOCATION_ID),
  CONSTRAINT EON_ORDER_ALLOCATION_UK1
 UNIQUE (ORDER_ID, SKU_ID)USING INDEX TABLESPACE EON_INDX01);

ALTER TABLE EON_ORDER_BILLING ADD (
  CONSTRAINT EON_ORDER_BILLING_PK
 PRIMARY KEY
 (ORDER_BILLING_ID),
  CONSTRAINT EON_ORDER_BILLING_UK1
 UNIQUE (ORDER_ID, SKU_ID)USING INDEX TABLESPACE EON_INDX01);

ALTER TABLE EON_ORDER_ITEM ADD (
  CONSTRAINT EON_ORDER_ITEM_PK
 PRIMARY KEY
 (ORDER_ITEM_ID),
  CONSTRAINT EON_ORDER_ITEM_UK1
 UNIQUE (ORDER_ID, SKU_ID)USING INDEX TABLESPACE EON_INDX01);

ALTER TABLE EON_ORDER_RECEIVED ADD (
  CONSTRAINT EON_ORDER_RECEIVED_PK
 PRIMARY KEY
 (ORDER_RECEIVED_ID),
  CONSTRAINT EON_ORDER_RECEIVED_UK1
 UNIQUE (ORDER_ID, SKU_ID)USING INDEX TABLESPACE EON_INDX01);

ALTER TABLE EON_ORDER_UNIT ADD (
  CONSTRAINT EON_ORDER_UNIT_PK
 PRIMARY KEY
 (ORDER_UNIT_ID)USING INDEX TABLESPACE EON_INDX01);

ALTER TABLE EON_PRODUCT_MASTER_FILE ADD (
  CONSTRAINT EON_PRODUCT_MASTER_FILE_PK
 PRIMARY KEY
 (PROD_MASTER_ID)USING INDEX TABLESPACE EON_INDX01);

ALTER TABLE EON_PRODUCT_MASTER_FILE_SKU ADD (
  CONSTRAINT EON_PRODUCT_MASTER_FILE_SKU_PK
 PRIMARY KEY
 (SKU_ID)USING INDEX TABLESPACE EON_INDX01);

ALTER TABLE EON_ROLES ADD (
  CONSTRAINT EON_ROLES_PK
 PRIMARY KEY
 (ROLE_ID)USING INDEX TABLESPACE EON_INDX01);

ALTER TABLE EON_SHEET_TYPE ADD (
  CONSTRAINT EON_SHEET_TYPE_PK
 PRIMARY KEY
 (SHEET_TYPE_ID)USING INDEX TABLESPACE EON_INDX01);

ALTER TABLE EON_SKU ADD (
  CONSTRAINT EON_SKU_PK
 PRIMARY KEY
 (SKU_ID)USING INDEX TABLESPACE EON_INDX01);

ALTER TABLE EON_SKU_COLUMN ADD (
  CONSTRAINT EON_SKU_COLUMN_PK
 PRIMARY KEY
 (SKU_COLUMN_ID)USING INDEX TABLESPACE EON_INDX01);

ALTER TABLE EON_SKU_GROUP ADD (
  CONSTRAINT EON_SKU_GROUP_PK
 PRIMARY KEY
 (SKU_GROUP_ID)USING INDEX TABLESPACE EON_INDX01);

ALTER TABLE EON_SORT_BUYERS ADD (
  CONSTRAINT EON_SORT_BUYERS_PK
 PRIMARY KEY
 (USER_ID, BUYER_ID)USING INDEX TABLESPACE EON_INDX01);

ALTER TABLE EON_SORT_SKU ADD (
  CONSTRAINT EON_SORT_SKU_PK
 PRIMARY KEY
 (USER_ID)USING INDEX TABLESPACE EON_INDX01);

ALTER TABLE EON_USERS ADD (
  CONSTRAINT EON_USERS_PK
 PRIMARY KEY
 (USER_ID),
  CONSTRAINT EON_USERS_UK1
 UNIQUE (USERNAME)USING INDEX TABLESPACE EON_INDX01);

ALTER TABLE EON_USER_DEALING_PATTERN ADD (
  CONSTRAINT EON_USER_DEALING_PATTERN_PK
 PRIMARY KEY
 (USER_DEALING_PATTERN_ID)USING INDEX TABLESPACE EON_INDX01);
 
ALTER TABLE EON_USER_PREF_FLAGS ADD (
  CONSTRAINT EON_USER_PREF_FLAGS_PK
 PRIMARY KEY
 (USER_PREF_ID)USING INDEX TABLESPACE EON_INDX01);
 
ALTER TABLE EON_FORGOT_PASSWORD_LINK ADD(
  CONSTRAINT EON_FORGOT_PASSWORD_LINK_PK
 PRIMARY KEY 
 (FORGOT_PASSWORD_LINK_ID)USING INDEX TABLESPACE EON_INDX01);
 
ALTER TABLE EON_EXCEL_SETTING ADD (
  CONSTRAINT EON_EXCEL_SETTING_PK
 PRIMARY KEY
 (USER_ID)USING INDEX TABLESPACE EON_INDX01); 

ALTER TABLE EON_ZIP_CODE ADD (
  CONSTRAINT EON_ZIP_CODE_PK
 PRIMARY KEY
 (ZIP_CODE)USING INDEX TABLESPACE EON_INDX01);
 
ALTER TABLE EON_AUDIT_TRAIL ADD (
  CONSTRAINT EON_AUDIT_TRAIL_PK
 PRIMARY KEY
 (ID)USING INDEX TABLESPACE EON_INDX01);
