ALTER TABLE EON_ADMIN_MEMBER ADD (
  CONSTRAINT EON_ADMIN_MEMBER_FK1 
 FOREIGN KEY (ADMIN_ID) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_ADMIN_MEMBER_FK2 
 FOREIGN KEY (MEMBER_ID) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_ADMIN_MEMBER_FK3 
 FOREIGN KEY (DEALING_PATTERN_RELATION_ID) 
 REFERENCES EON_DEALING_PATTERN_RELATION (DEALING_PATTERN_RELATION_ID),
  CONSTRAINT EON_ADMIN_MEMBER_FK4
 FOREIGN KEY (CREATED_BY) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_ADMIN_MEMBER_FK5
 FOREIGN KEY (UPDATED_BY) 
 REFERENCES EON_USERS (USER_ID) );

ALTER TABLE EON_AKADEN_SKU ADD (
  CONSTRAINT EON_AKADEN_SKU_FK1 
 FOREIGN KEY (SKU_ID) 
 REFERENCES EON_SKU (SKU_ID),
  CONSTRAINT EON_AKADEN_SKU_FK2 
 FOREIGN KEY (SELLER_ID) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_AKADEN_SKU_FK3 
 FOREIGN KEY (SKU_CATEGORY_ID) 
 REFERENCES EON_CATEGORY (SKU_CATEGORY_ID),
  CONSTRAINT EON_AKADEN_SKU_FK4 
 FOREIGN KEY (SKU_GROUP_ID) 
 REFERENCES EON_SKU_GROUP (SKU_GROUP_ID),
  CONSTRAINT EON_AKADEN_SKU_FK5 
 FOREIGN KEY (ORDER_UNIT_ID) 
 REFERENCES EON_ORDER_UNIT (ORDER_UNIT_ID),
  CONSTRAINT EON_AKADEN_SKU_FK6 
 FOREIGN KEY (PROPOSED_BY) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_AKADEN_SKU_FK7
 FOREIGN KEY (SHEET_TYPE_ID) 
 REFERENCES EON_SHEET_TYPE (SHEET_TYPE_ID),
  CONSTRAINT EON_AKADEN_SKU_FK8
 FOREIGN KEY (CREATED_BY) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_AKADEN_SKU_FK9
 FOREIGN KEY (UPDATED_BY) 
 REFERENCES EON_USERS (USER_ID));
  
ALTER TABLE EON_COMMENTS_INBOX ADD (
  CONSTRAINT EON_COMMENTS_INBOX_FK1 
 FOREIGN KEY (SENDER_ENTITY_ID) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_COMMENTS_INBOX_FK2
 FOREIGN KEY (RECIPIENT_ENTITY_ID) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_COMMENTS_INBOX_FK3
 FOREIGN KEY (CREATE_USER_ID) 
 REFERENCES EON_USERS (USER_ID), 
  CONSTRAINT EON_COMMENTS_INBOX_FK4
 FOREIGN KEY (UPDATED_BY) 
 REFERENCES EON_USERS (USER_ID)); 
 
ALTER TABLE EON_COMMENTS_OUTBOX ADD (
  CONSTRAINT EON_COMMENTS_OUTBOX_FK1 
 FOREIGN KEY (SENDER_ENTITY_ID) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_COMMENTS_OUTBOX_FK2
 FOREIGN KEY (CREATE_USER_ID) 
 REFERENCES EON_USERS (USER_ID), 
  CONSTRAINT EON_COMMENTS_OUTBOX_FK3
 FOREIGN KEY (UPDATED_BY) 
 REFERENCES EON_USERS (USER_ID)); 

ALTER TABLE EON_COMPANY ADD (
  CONSTRAINT EON_COMPANY_FK1
 FOREIGN KEY (CREATED_BY) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_COMPANY_FK2
 FOREIGN KEY (UPDATED_BY) 
 REFERENCES EON_USERS (USER_ID),
 CONSTRAINT EON_COMPANY_FK3
 FOREIGN KEY (COMPANY_TYPE_ID) 
 REFERENCES EON_COMPANY_TYPE (COMPANY_TYPE_ID) ); 
 
ALTER TABLE EON_COMPANY_DEALING_PATTERN ADD (
  CONSTRAINT EON_COMPANYDEALINGPATTERN_FK1 
 FOREIGN KEY (COMPANY_01) 
 REFERENCES EON_COMPANY (COMPANY_ID),
  CONSTRAINT EON_COMPANYDEALINGPATTERN_FK2 
 FOREIGN KEY (COMPANY_02) 
 REFERENCES EON_COMPANY (COMPANY_ID),
  CONSTRAINT EON_COMPANYDEALINGPATTERN_FK3 
 FOREIGN KEY (DEALING_PATTERN_RELATION_ID) 
 REFERENCES EON_DEALING_PATTERN_RELATION (DEALING_PATTERN_RELATION_ID), 
  CONSTRAINT EON_COMPANYDEALINGPATTERN_FK4
 FOREIGN KEY (CREATED_BY) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_COMPANYDEALINGPATTERN_FK5
 FOREIGN KEY (UPDATED_BY) 
 REFERENCES EON_USERS (USER_ID));

ALTER TABLE EON_ORDER ADD (
  CONSTRAINT EON_ORDER_FK1 
 FOREIGN KEY (BUYER_ID) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_ORDER_FK2
 FOREIGN KEY (SELLER_ID) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_ORDER_FK3			-- orders
 FOREIGN KEY (ORDER_SAVED_BY) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_ORDER_FK4
 FOREIGN KEY (ORDER_PUBLISHED_BY) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_ORDER_FK5
 FOREIGN KEY (ORDER_FINALIZED_BY) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_ORDER_FK6
 FOREIGN KEY (ORDER_UNFINALIZED_BY) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_ORDER_FK7
 FOREIGN KEY (ORDER_LOCKED_BY) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_ORDER_FK8
 FOREIGN KEY (ORDER_UNLOCKED_BY) 
 REFERENCES EON_USERS (USER_ID), 
  CONSTRAINT EON_ORDER_FK9			-- allocation
 FOREIGN KEY (ALLOCATION_SAVED_BY) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_ORDER_FK10
 FOREIGN KEY (ALLOCATION_PUBLISHED_BY) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_ORDER_FK11
 FOREIGN KEY (ALLOCATION_FINALIZED_BY) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_ORDER_FK12
 FOREIGN KEY (ALLOCATION_UNFINALIZED_BY) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_ORDER_FK13			-- received
 FOREIGN KEY (RECEIVED_APPROVED_BY) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_ORDER_FK14
 FOREIGN KEY (RECEIVED_UNAPPROVED_BY) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_ORDER_FK15			
 FOREIGN KEY (RECEIVED_SAVED_BY) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_ORDER_FK16			-- billing
 FOREIGN KEY (BILLING_SAVED_BY) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_ORDER_FK17
 FOREIGN KEY (BILLING_FINALIZED_BY) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_ORDER_FK18
 FOREIGN KEY (BILLING_UNFINALIZED_BY) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_ORDER_FK19
 FOREIGN KEY (AKADEN_SAVED_BY) 
 REFERENCES EON_USERS (USER_ID), 
  CONSTRAINT EON_ORDER_FK20
 FOREIGN KEY (ORDER_PUBLISHED_BY_BA) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_ORDER_FK21
 FOREIGN KEY (CREATED_BY) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_ORDER_FK22
 FOREIGN KEY (UPDATED_BY) 
 REFERENCES EON_USERS (USER_ID));  
 
ALTER TABLE EON_ORDER_AKADEN ADD (
  CONSTRAINT EON_ORDER_AKADEN_FK1 
 FOREIGN KEY (AKADEN_SKU_ID) 
 REFERENCES EON_AKADEN_SKU (AKADEN_SKU_ID),
  CONSTRAINT EON_ORDER_AKADEN_FK2 
 FOREIGN KEY (ORDER_ID) 
 REFERENCES EON_ORDER (ORDER_ID),
  CONSTRAINT EON_ORDER_AKADEN_FK3
 FOREIGN KEY (CREATED_BY) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_ORDER_AKADEN_FK4 
 FOREIGN KEY (UPDATE_BY) 
 REFERENCES EON_USERS (USER_ID));

ALTER TABLE EON_ORDER_ALLOCATION ADD (
  CONSTRAINT EON_ORDER_ALLOCATION_FK1 
 FOREIGN KEY (ORDER_ID) 
 REFERENCES EON_ORDER (ORDER_ID),
  CONSTRAINT EON_ORDER_ALLOCATION_FK2 
 FOREIGN KEY (SKU_ID) 
 REFERENCES EON_SKU (SKU_ID),
  CONSTRAINT EON_ORDER_ALLOCATION_FK3
 FOREIGN KEY (CREATED_BY) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_ORDER_ALLOCATION_FK4 
 FOREIGN KEY (UPDATED_BY) 
 REFERENCES EON_USERS (USER_ID));

ALTER TABLE EON_ORDER_BILLING ADD (
  CONSTRAINT EON_ORDER_BILLING_FK1 
 FOREIGN KEY (ORDER_ID) 
 REFERENCES EON_ORDER (ORDER_ID),
  CONSTRAINT EON_ORDER_BILLING_FK2 
 FOREIGN KEY (SKU_ID) 
 REFERENCES EON_SKU (SKU_ID),
  CONSTRAINT EON_ORDER_BILLING_FK3
 FOREIGN KEY (CREATED_BY) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_ORDER_BILLING_FK4 
 FOREIGN KEY (UPDATED_BY) 
 REFERENCES EON_USERS (USER_ID));

ALTER TABLE EON_ORDER_ITEM ADD (
  CONSTRAINT EON_ORDER_ITEM_FK1 
 FOREIGN KEY (ORDER_ID) 
 REFERENCES EON_ORDER (ORDER_ID),
  CONSTRAINT EON_ORDER_ITEM_FK2 
 FOREIGN KEY (SKU_ID) 
 REFERENCES EON_SKU (SKU_ID),
  CONSTRAINT EON_ORDER_ITEM_FK3
 FOREIGN KEY (CREATED_BY) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_ORDER_ITEM_FK4
 FOREIGN KEY (UPDATE_BY_USERS_ID) 
 REFERENCES EON_USERS (USER_ID));

ALTER TABLE EON_ORDER_RECEIVED ADD (
  CONSTRAINT EON_ORDER_RECEIVED_FK1 
 FOREIGN KEY (ORDER_ID) 
 REFERENCES EON_ORDER (ORDER_ID),
  CONSTRAINT EON_ORDER_RECEIVED_FK2
 FOREIGN KEY (SKU_ID) 
 REFERENCES EON_SKU (SKU_ID),
  CONSTRAINT EON_ORDER_RECEIVED_FK3
 FOREIGN KEY (CREATED_BY) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_ORDER_RECEIVED_FK4 
 FOREIGN KEY (UPDATED_BY) 
 REFERENCES EON_USERS (USER_ID));

ALTER TABLE EON_ORDER_UNIT ADD (
  CONSTRAINT EON_ORDER_UNIT_FK1 
 FOREIGN KEY (CATEGORY_ID) 
 REFERENCES EON_CATEGORY (SKU_CATEGORY_ID)); 
 
ALTER TABLE EON_PRODUCT_MASTER_FILE ADD (
  CONSTRAINT EON_PRODUCT_MASTER_FILE_FK1 
 FOREIGN KEY (USER_ID) 
 REFERENCES EON_USERS (USER_ID));

ALTER TABLE EON_PRODUCT_MASTER_FILE_SKU ADD (
  CONSTRAINT EON_PRODUCT_MASTER_FILESKU_FK2 
 FOREIGN KEY (PROD_MASTER_ID) 
 REFERENCES EON_PRODUCT_MASTER_FILE (PROD_MASTER_ID),
  CONSTRAINT EON_PRODUCT_MASTER_FILESKU_FK3 
 FOREIGN KEY (SELLER_ID) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_PRODUCT_MASTER_FILESKU_FK4 
 FOREIGN KEY (SKU_CATEGORY_ID) 
 REFERENCES EON_CATEGORY (SKU_CATEGORY_ID),
  CONSTRAINT EON_PRODUCT_MASTER_FILESKU_FK5 
 FOREIGN KEY (SKU_GROUP_ID) 
 REFERENCES EON_SKU_GROUP (SKU_GROUP_ID),
  CONSTRAINT EON_PRODUCT_MASTER_FILESKU_FK6 
 FOREIGN KEY (ORDER_UNIT_ID) 
 REFERENCES EON_ORDER_UNIT (ORDER_UNIT_ID),
  CONSTRAINT EON_PRODUCT_MASTER_FILESKU_FK7
 FOREIGN KEY (CREATED_BY) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_PRODUCT_MASTER_FILESKU_FK8
 FOREIGN KEY (UPDATED_BY) 
 REFERENCES EON_USERS (USER_ID));

ALTER TABLE EON_SHEET_TYPE ADD (
  CONSTRAINT EON_SHEET_TYPE_FK1 
 FOREIGN KEY (ROLE_ID) 
 REFERENCES EON_ROLES (ROLE_ID));
 
ALTER TABLE EON_SKU ADD (
  CONSTRAINT EON_SKU_FK1 
 FOREIGN KEY (SHEET_TYPE_ID) 
 REFERENCES EON_SHEET_TYPE (SHEET_TYPE_ID),
  CONSTRAINT EON_SKU_FK2 
 FOREIGN KEY (SKU_CATEGORY_ID) 
 REFERENCES EON_CATEGORY (SKU_CATEGORY_ID),
  CONSTRAINT EON_SKU_FK3 
 FOREIGN KEY (SELLER_ID) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_SKU_FK4 
 FOREIGN KEY (ORIGINAL_SKU_ID) 
 REFERENCES EON_SKU (SKU_ID),
  CONSTRAINT EON_SKU_FK5 
 FOREIGN KEY (PROPOSED_BY) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_SKU_FK6 
 FOREIGN KEY (SKU_GROUP_ID) 
 REFERENCES EON_SKU_GROUP (SKU_GROUP_ID),
  CONSTRAINT EON_SKU_FK7 
 FOREIGN KEY (ORDER_UNIT_ID) 
 REFERENCES EON_ORDER_UNIT (ORDER_UNIT_ID),
  CONSTRAINT EON_SKU_FK8
 FOREIGN KEY (CREATED_BY) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_SKU_FK9
 FOREIGN KEY (UPDATED_BY) 
 REFERENCES EON_USERS (USER_ID));

ALTER TABLE EON_SKU_GROUP ADD (
  CONSTRAINT EON_SKU_GROUP_FK1 
 FOREIGN KEY (SKU_CATEGORY_ID) 
 REFERENCES EON_CATEGORY (SKU_CATEGORY_ID),
  CONSTRAINT EON_SKU_GROUP_FK2 
 FOREIGN KEY (SELLER_ID) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_SKU_GROUP_FK3 
 FOREIGN KEY (ORIG_SKU_GROUP_ID) 
 REFERENCES EON_SKU_GROUP (SKU_GROUP_ID),
  CONSTRAINT EON_SKU_GROUP_FK4
 FOREIGN KEY (CREATED_BY) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_SKU_GROUP_FK5
 FOREIGN KEY (UPDATED_BY) 
 REFERENCES EON_USERS (USER_ID));
 
ALTER TABLE EON_SORT_BUYERS ADD (
  CONSTRAINT EON_SORT_BUYERS_FK1
 FOREIGN KEY (USER_ID) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_SORT_BUYERS_FK2
 FOREIGN KEY (BUYER_ID) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_SORT_BUYERS_FK3
 FOREIGN KEY (CREATED_BY) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_SORT_BUYERS_FK4
 FOREIGN KEY (UPDATED_BY) 
 REFERENCES EON_USERS (USER_ID));
 
ALTER TABLE EON_SORT_COMPANY_BUYERS ADD (
  CONSTRAINT EON_SORT_COMPANY_BUYERS_FK1
 FOREIGN KEY (USER_ID) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_SORT_COMPANY_BUYERS_FK2
 FOREIGN KEY (COMPANY_ID) 
 REFERENCES EON_COMPANY (COMPANY_ID),
  CONSTRAINT EON_SORT_COMPANY_BUYERS_FK3
 FOREIGN KEY (CREATED_BY) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_SORT_COMPANY_BUYERS_FK4
 FOREIGN KEY (UPDATED_BY) 
 REFERENCES EON_USERS (USER_ID));

ALTER TABLE EON_SORT_SKU ADD (
  CONSTRAINT EON_SORT_SKU_FK1 
 FOREIGN KEY (USER_ID) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_SORT_SKU_FK2
 FOREIGN KEY (CREATED_BY) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_SORT_SKU_FK3
 FOREIGN KEY (UPDATED_BY) 
 REFERENCES EON_USERS (USER_ID));

ALTER TABLE EON_SORT_SKU_GROUP ADD (
  CONSTRAINT EON_SORT_SKU_GROUP_FK1 
 FOREIGN KEY (USER_ID) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_SORT_SKU_GROUP_FK2 
 FOREIGN KEY (SKU_CATEGORY_ID) 
 REFERENCES EON_CATEGORY (SKU_CATEGORY_ID),
  CONSTRAINT EON_SORT_SKU_GROUP_FK3 
 FOREIGN KEY (SKU_GROUP_ID) 
 REFERENCES EON_SKU_GROUP (SKU_GROUP_ID),
  CONSTRAINT EON_SORT_SKU_GROUP_FK4
 FOREIGN KEY (CREATED_BY) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_SORT_SKU_GROUP_FK5
 FOREIGN KEY (UPDATED_BY) 
 REFERENCES EON_USERS (USER_ID));

ALTER TABLE EON_USERS ADD (
  CONSTRAINT EON_USERS_FK1 
 FOREIGN KEY (COMPANY_ID) 
 REFERENCES EON_COMPANY (COMPANY_ID),
  CONSTRAINT EON_USERS_FK2 
 FOREIGN KEY (ROLE_ID) 
 REFERENCES EON_ROLES (ROLE_ID),
  CONSTRAINT EON_USERS_FK3
 FOREIGN KEY (CREATED_BY) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_USERS_FK4
 FOREIGN KEY (UPDATED_BY) 
 REFERENCES EON_USERS (USER_ID) );

ALTER TABLE EON_USERS_CATEGORY ADD (
  CONSTRAINT EON_USERS_CATEGORY_FK1 
 FOREIGN KEY (USER_ID) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_USERS_CATEGORY_FK2 
 FOREIGN KEY (CATEGORY_ID) 
 REFERENCES EON_CATEGORY (SKU_CATEGORY_ID));

ALTER TABLE EON_USER_DEALING_PATTERN ADD (
  CONSTRAINT EON_USER_DEALING_PATTERN_FK1 
 FOREIGN KEY (COMPANY_DEALING_PATTERN_ID) 
 REFERENCES EON_COMPANY_DEALING_PATTERN (COMPANY_DEALING_PATTERN_ID),
  CONSTRAINT EON_USER_DEALING_PATTERN_FK2 
 FOREIGN KEY (DEALING_PATTERN_RELATION_ID) 
 REFERENCES EON_DEALING_PATTERN_RELATION (DEALING_PATTERN_RELATION_ID),
  CONSTRAINT EON_USER_DEALING_PATTERN_FK3 
 FOREIGN KEY (USER_01) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_USER_DEALING_PATTERN_FK4 
 FOREIGN KEY (USER_02) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_USER_DEALING_PATTERN_FK5
 FOREIGN KEY (CREATED_BY) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_USER_DEALING_PATTERN_FK6
 FOREIGN KEY (UPDATED_BY) 
 REFERENCES EON_USERS (USER_ID));

ALTER TABLE EON_USER_PREF_FLAGS ADD (
  CONSTRAINT EON_USER_PREF_FLAGS_FK1 
 FOREIGN KEY (USER_ID) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_USER_PREF_FLAGS_FK2
 FOREIGN KEY (CREATED_BY) 
 REFERENCES EON_USERS (USER_ID),
  CONSTRAINT EON_USER_PREF_FLAGS_FK3
 FOREIGN KEY (UPDATED_BY) 
 REFERENCES EON_USERS (USER_ID));

ALTER TABLE EON_FORGOT_PASSWORD_LINK ADD (
CONSTRAINT EON_FORGOT_PASSWORD_LINK_FK1 
FOREIGN KEY (USER_ID) 
REFERENCES EON_USERS (USER_ID));

ALTER TABLE EON_EXCEL_SETTING ADD (
CONSTRAINT EON_EXCEL_SETTING_FK1 
FOREIGN KEY (USER_ID) 
REFERENCES EON_USERS (USER_ID));


