Insert into EON_CATEGORY
   (SKU_CATEGORY_ID, DESCRIPTION)
 Values
   (EON_SKU_CATEGORY_SEQ.NEXTVAL, 'Fruits');
Insert into EON_CATEGORY
   (SKU_CATEGORY_ID, DESCRIPTION)
 Values
   (EON_SKU_CATEGORY_SEQ.NEXTVAL, 'Vegetables');
Insert into EON_CATEGORY
   (SKU_CATEGORY_ID, DESCRIPTION)
 Values
   (EON_SKU_CATEGORY_SEQ.NEXTVAL, 'Fish');
COMMIT;
