Insert into EON_DEALING_PATTERN_RELATION
   (DEALING_PATTERN_RELATION_ID, DESCRIPTION)
 Values
   (10000, 'SELLER-BUYER');
Insert into EON_DEALING_PATTERN_RELATION
   (DEALING_PATTERN_RELATION_ID, DESCRIPTION)
 Values
   (10002, 'BUYERADMIN-BUYER');
Insert into EON_DEALING_PATTERN_RELATION
   (DEALING_PATTERN_RELATION_ID, DESCRIPTION)
 Values
   (10003, 'SELLERADMIN-SELLER');
Insert into EON_DEALING_PATTERN_RELATION
   (DEALING_PATTERN_RELATION_ID, DESCRIPTION)
 Values
   (10004, 'CHOUAI-SELLER');
COMMIT;
