-- uat_sb1 / 30
-- uat_bb1 / 41
-- order_id = 31

-- uat_sb1 / 30
-- uat_bb2 / 42
-- order_id = 32

-- uat_sb1 / 30
-- uat_bb3 / 43
-- order_id = 33

INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 31, 1591, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 32, 1591, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 33, 1591, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 31, 1592, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 32, 1592, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 33, 1592, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 31, 1593, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 32, 1593, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 33, 1593, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 31, 1594, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 32, 1594, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 33, 1594, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 31, 1595, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 32, 1595, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 33, 1595, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 31, 1596, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 32, 1596, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 33, 1596, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 31, 1597, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 32, 1597, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 33, 1597, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 31, 1598, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 32, 1598, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 33, 1598, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 31, 1599, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 32, 1599, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 33, 1599, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 31, 1600, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 32, 1600, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 33, 1600, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 31, 1601, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 32, 1601, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 33, 1601, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 31, 1602, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 32, 1602, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 33, 1602, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 31, 1603, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 32, 1603, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 33, 1603, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 31, 1604, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 32, 1604, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 33, 1604, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 31, 1605, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 32, 1605, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 33, 1605, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 31, 1606, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 32, 1606, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 33, 1606, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 31, 1607, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 32, 1607, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 33, 1607, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 31, 1608, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 32, 1608, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 33, 1608, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 31, 1609, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 32, 1609, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 33, 1609, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 31, 1610, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 32, 1610, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 33, 1610, 5, '1', '1'); 


COMMIT;