-- s_cb01 / 8
-- fruits / 1
-- piece / 1
-- sku_fruit_001 / 55
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 8,
   55, 1, 10001, 1,
   'TestDataFruits001', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 8);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 8,
   55, 1, 10001, 1,
   'TestDataFruits002', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 8);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 8,
   55, 1, 10001, 1,
   'TestDataFruits003', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 8);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 8,
   55, 1, 10001, 1,
   'TestDataFruits004', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 8);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 8,
   55, 1, 10001, 1,
   'TestDataFruits005', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 8);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 8,
   55, 1, 10001, 1,
   'TestDataFruits006', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 8);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 8,
   55, 1, 10001, 1,
   'TestDataFruits007', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 8);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 8,
   55, 1, 10001, 1,
   'TestDataFruits008', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 8);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 8,
   55, 1, 10001, 1,
   'TestDataFruits009', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 8);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 8,
   55, 1, 10001, 1,
   'TestDataFruits010', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 8);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 8,
   55, 1, 10001, 1,
   'TestDataFruits011', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 8);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 8,
   55, 1, 10001, 1,
   'TestDataFruits012', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 8);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 8,
   55, 1, 10001, 1,
   'TestDataFruits013', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 8);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 8,
   55, 1, 10001, 1,
   'TestDataFruits014', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 8);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 8,
   55, 1, 10001, 1,
   'TestDataFruits015', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 8);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 8,
   55, 1, 10001, 1,
   'TestDataFruits016', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 8);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 8,
   55, 1, 10001, 1,
   'TestDataFruits017', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 8);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 8,
   55, 1, 10001, 1,
   'TestDataFruits018', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 8);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 8,
   55, 1, 10001, 1,
   'TestDataFruits019', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 8);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 8,
   55, 1, 10001, 1,
   'TestDataFruits020', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 8);
COMMIT;