-- order id = 13
-- s_cb01
-- b_cb01
-- fruits
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 13, 766, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 13, 767, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 13, 768, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 13, 769, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 13, 770, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 13, 771, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 13, 772, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 13, 773, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 13, 774, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 13, 775, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 13, 776, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 13, 777, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 13, 778, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 13, 779, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 13, 780, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 13, 781, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 13, 782, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 13, 783, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 13, 784, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 13, 785, 5, '1', '1');

-- order id = 14
-- s_cb01
-- b_cb02
-- fruits
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 14, 766, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 14, 767, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 14, 768, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 14, 769, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 14, 770, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 14, 771, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 14, 772, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 14, 773, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 14, 774, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 14, 775, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 14, 776, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 14, 777, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 14, 778, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 14, 779, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 14, 780, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 14, 781, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 14, 782, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 14, 783, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 14, 784, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 14, 785, 5, '1', '1');

-- order id = 15
-- s_cb01
-- b_cb03
-- fruits
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 15, 766, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 15, 767, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 15, 768, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 15, 769, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 15, 770, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 15, 771, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 15, 772, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 15, 773, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 15, 774, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 15, 775, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 15, 776, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 15, 777, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 15, 778, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 15, 779, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 15, 780, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 15, 781, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 15, 782, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 15, 783, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 15, 784, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 15, 785, 5, '1', '1');
COMMIT;