-- s_ca02
-- b_ca01
-- fruits
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 7, 36, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 7, 37, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 7, 38, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 7, 39, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 7, 40, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 7, 41, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 7, 42, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 7, 43, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 7, 44, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 7, 45, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 7, 46, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 7, 47, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 7, 48, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 7, 49, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 7, 50, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 7, 51, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 7, 52, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 7, 53, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 7, 54, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 7, 55, 5, '1', '1');
-- vegetables
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 7, 56, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 7, 57, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 7, 58, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 7, 59, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 7, 60, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 7, 61, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 7, 62, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 7, 63, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 7, 64, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 7, 65, 5, '1', '1');
-- fish
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 7, 66, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 7, 67, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 7, 68, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 7, 69, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 7, 70, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 7, 71, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 7, 72, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 7, 73, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 7, 74, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 7, 75, 5, '1', '1');

-- s_ca02
-- b_ca02
-- fruits
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 8, 36, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 8, 37, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 8, 38, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 8, 39, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 8, 40, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 8, 41, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 8, 42, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 8, 43, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 8, 44, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 8, 45, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 8, 46, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 8, 47, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 8, 48, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 8, 49, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 8, 50, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 8, 51, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 8, 52, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 8, 53, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 8, 54, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 8, 55, 5, '1', '1');
-- vegetables
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 8, 56, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 8, 57, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 8, 58, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 8, 59, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 8, 60, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 8, 61, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 8, 62, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 8, 63, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 8, 64, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 8, 65, 5, '1', '1');
-- fish
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 8, 66, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 8, 67, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 8, 68, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 8, 69, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 8, 70, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 8, 71, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 8, 72, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 8, 73, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 8, 74, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 8, 75, 5, '1', '1');

 	
-- s_ca02
-- b_cb01
-- fruits
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 9, 36, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 9, 37, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 9, 38, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 9, 39, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 9, 40, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 9, 41, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 9, 42, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 9, 43, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 9, 44, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 9, 45, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 9, 46, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 9, 47, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 9, 48, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 9, 49, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 9, 50, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 9, 51, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 9, 52, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 9, 53, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 9, 54, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 9, 55, 5, '1', '1');
-- vegetables
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 9, 56, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 9, 57, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 9, 58, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 9, 59, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 9, 60, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 9, 61, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 9, 62, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 9, 63, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 9, 64, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 9, 65, 5, '1', '1');
-- fish
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 9, 66, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 9, 67, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 9, 68, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 9, 69, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 9, 70, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 9, 71, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 9, 72, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 9, 73, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 9, 74, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 9, 75, 5, '1', '1');
 	
-- s_ca02
-- b_cb02
-- fruits
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 10, 36, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 10, 37, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 10, 38, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 10, 39, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 10, 40, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 10, 41, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 10, 42, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 10, 43, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 10, 44, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 10, 45, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 10, 46, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 10, 47, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 10, 48, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 10, 49, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 10, 50, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 10, 51, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 10, 52, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 10, 53, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 10, 54, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 10, 55, 5, '1', '1');
-- vegetables
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 10, 56, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 10, 57, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 10, 58, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 10, 59, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 10, 60, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 10, 61, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 10, 62, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 10, 63, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 10, 64, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 10, 65, 5, '1', '1');
-- fish
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 10, 66, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 10, 67, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 10, 68, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 10, 69, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 10, 70, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 10, 71, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 10, 72, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 10, 73, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 10, 74, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 10, 75, 5, '1', '1');
COMMIT;