-- s_ca01
-- fruits
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 2,
   1, 'sku_fruit_001', '20100101', 2);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 2,
   1, 'sku_fruit_002', '20100101', 2);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 2,
   1, 'sku_fruit_003', '20100101', 2);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 2,
   1, 'sku_fruit_004', '20100101', 2);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 2,
   1, 'sku_fruit_005', '20100101', 2);

-- vegetables
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 2,
   2, 'sku_vege_001', '20100101', 2);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 2,
   2, 'sku_vege_002', '20100101', 2);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 2,
   2, 'sku_vege_003', '20100101', 2);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 2,
   2, 'sku_vege_004', '20100101', 2);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 2,
   2, 'sku_vege_005', '20100101', 2);

-- fishes
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 2,
   3, 'sku_fish_001', '20100101', 2);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 2,
   3, 'sku_fish_002', '20100101', 2);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 2,
   3, 'sku_fish_003', '20100101', 2);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 2,
   3, 'sku_fish_004', '20100101', 2);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 2,
   3, 'sku_fish_005', '20100101', 2);
   
   
-- s_ca02
-- fruits
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 3,
   1, 'sku_fruit_001', '20100101', 3);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 3,
   1, 'sku_fruit_002', '20100101', 3);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 3,
   1, 'sku_fruit_003', '20100101', 3);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 3,
   1, 'sku_fruit_004', '20100101', 3);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 3,
   1, 'sku_fruit_005', '20100101', 3);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 3,
   1, 'sku_fruit_006', '20100101', 3);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 3,
   1, 'sku_fruit_007', '20100101', 3);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 3,
   1, 'sku_fruit_008', '20100101', 3);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 3,
   1, 'sku_fruit_009', '20100101', 3);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 3,
   1, 'sku_fruit_010', '20100101', 3);

-- vegetables
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 3,
   2, 'sku_vege_001', '20100101', 3);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 3,
   2, 'sku_vege_002', '20100101', 3);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 3,
   2, 'sku_vege_003', '20100101', 3);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 3,
   2, 'sku_vege_004', '20100101', 3);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 3,
   2, 'sku_vege_005', '20100101', 3);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 3,
   2, 'sku_vege_006', '20100101', 3);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 3,
   2, 'sku_vege_007', '20100101', 3);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 3,
   2, 'sku_vege_008', '20100101', 3);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 3,
   2, 'sku_vege_009', '20100101', 3);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 3,
   2, 'sku_vege_010', '20100101', 3);

-- fishes
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 3,
   3, 'sku_fish_001', '20100101', 3);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 3,
   3, 'sku_fish_002', '20100101', 3);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 3,
   3, 'sku_fish_003', '20100101', 3);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 3,
   3, 'sku_fish_004', '20100101', 3);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 3,
   3, 'sku_fish_005', '20100101', 3);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 3,
   3, 'sku_fish_006', '20100101', 3);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 3,
   3, 'sku_fish_007', '20100101', 3);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 3,
   3, 'sku_fish_008', '20100101', 3);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 3,
   3, 'sku_fish_009', '20100101', 3);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 3,
   3, 'sku_fish_010', '20100101', 3);
   
-- s_ca03
-- fruits
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 4,
   1, 'sku_fruit_001', '20100101', 4);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 4,
   1, 'sku_fruit_002', '20100101', 4);


-- vegetables
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 4,
   2, 'sku_vege_001', '20100101', 4);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 4,
   2, 'sku_vege_002', '20100101', 4);

-- fishes
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 4,
   3, 'sku_fish_001', '20100101', 4);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 4,
   3, 'sku_fish_002', '20100101', 4);

   
-- s_cb01
-- fruits
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 8,
   1, 'sku_fruit_001', '20100101', 8);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 8,
   1, 'sku_fruit_002', '20100101', 8);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 8,
   1, 'sku_fruit_003', '20100101', 8);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 8,
   1, 'sku_fruit_004', '20100101', 8);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 8,
   1, 'sku_fruit_005', '20100101', 8);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 8,
   1, 'sku_fruit_006', '20100101', 8);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 8,
   1, 'sku_fruit_007', '20100101', 8);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 8,
   1, 'sku_fruit_008', '20100101', 8);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 8,
   1, 'sku_fruit_009', '20100101', 8);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 8,
   1, 'sku_fruit_010', '20100101', 8);

-- vegetables
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 9,
   2, 'sku_vege_001', '20100101', 9);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 9,
   2, 'sku_vege_002', '20100101', 9);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 9,
   2, 'sku_vege_003', '20100101', 9);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 9,
   2, 'sku_vege_004', '20100101', 9);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 9,
   2, 'sku_vege_005', '20100101', 9);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 9,
   2, 'sku_vege_006', '20100101', 9);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 9,
   2, 'sku_vege_007', '20100101', 9);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 9,
   2, 'sku_vege_008', '20100101', 9);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 9,
   2, 'sku_vege_009', '20100101', 9);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 9,
   2, 'sku_vege_010', '20100101', 9);

-- fishes
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 10,
   3, 'sku_fish_001', '20100101', 10);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 10,
   3, 'sku_fish_002', '20100101', 10);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 10,
   3, 'sku_fish_003', '20100101', 10);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 10,
   3, 'sku_fish_004', '20100101', 10);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 10,
   3, 'sku_fish_005', '20100101', 10);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 10,
   3, 'sku_fish_006', '20100101', 10);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 10,
   3, 'sku_fish_007', '20100101', 10);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 10,
   3, 'sku_fish_008', '20100101', 10);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 10,
   3, 'sku_fish_009', '20100101', 10);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 10,
   3, 'sku_fish_010', '20100101', 10);

-- UAT SKU Groups
-- uat_sa1
-- fruits
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 24,
   1, 'sku_fruit_001', '20100101', 24);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 24,
   1, 'sku_fruit_002', '20100101', 24);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 24,
   1, 'sku_fruit_003', '20100101', 24);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 24,
   1, 'sku_fruit_004', '20100101', 24);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 24,
   1, 'sku_fruit_005', '20100101', 24);

-- vegetables
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 24,
   2, 'sku_vege_001', '20100101', 24);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 24,
   2, 'sku_vege_002', '20100101', 24);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 24,
   2, 'sku_vege_003', '20100101', 24);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 24,
   2, 'sku_vege_004', '20100101', 24);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 24,
   2, 'sku_vege_005', '20100101', 24);

-- fishes
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 24,
   3, 'sku_fish_001', '20100101', 24);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 24,
   3, 'sku_fish_002', '20100101', 24);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 24,
   3, 'sku_fish_003', '20100101', 24);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 24,
   3, 'sku_fish_004', '20100101', 24);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 24,
   3, 'sku_fish_005', '20100101', 24);
   
   
-- uat_sa2
-- fruits
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 25,
   1, 'sku_fruit_001', '20100101', 25);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 25,
   1, 'sku_fruit_002', '20100101', 25);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 25,
   1, 'sku_fruit_003', '20100101', 25);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 25,
   1, 'sku_fruit_004', '20100101', 25);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 25,
   1, 'sku_fruit_005', '20100101', 25);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 25,
   1, 'sku_fruit_006', '20100101', 25);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 25,
   1, 'sku_fruit_007', '20100101', 25);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 25,
   1, 'sku_fruit_008', '20100101', 25);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 25,
   1, 'sku_fruit_009', '20100101', 25);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 25,
   1, 'sku_fruit_010', '20100101', 25);

-- vegetables
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 25,
   2, 'sku_vege_001', '20100101', 25);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 25,
   2, 'sku_vege_002', '20100101', 25);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 25,
   2, 'sku_vege_003', '20100101', 25);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 25,
   2, 'sku_vege_004', '20100101', 25);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 25,
   2, 'sku_vege_005', '20100101', 25);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 25,
   2, 'sku_vege_006', '20100101', 25);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 25,
   2, 'sku_vege_007', '20100101', 25);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 25,
   2, 'sku_vege_008', '20100101', 25);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 25,
   2, 'sku_vege_009', '20100101', 25);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 25,
   2, 'sku_vege_010', '20100101', 25);

-- fishes
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 25,
   3, 'sku_fish_001', '20100101', 25);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 25,
   3, 'sku_fish_002', '20100101', 25);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 25,
   3, 'sku_fish_003', '20100101', 25);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 25,
   3, 'sku_fish_004', '20100101', 25);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 25,
   3, 'sku_fish_005', '20100101', 25);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 25,
   3, 'sku_fish_006', '20100101', 25);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 25,
   3, 'sku_fish_007', '20100101', 25);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 25,
   3, 'sku_fish_008', '20100101', 25);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 25,
   3, 'sku_fish_009', '20100101', 25);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 25,
   3, 'sku_fish_010', '20100101', 25);
   
-- uat_sa3
-- fruits
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 26,
   1, 'sku_fruit_001', '20100101', 26);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 26,
   1, 'sku_fruit_002', '20100101', 26);


-- vegetables
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 26,
   2, 'sku_vege_001', '20100101', 26);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 26,
   2, 'sku_vege_002', '20100101', 26);

-- fishes
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 26,
   3, 'sku_fish_001', '20100101', 26);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 26,
   3, 'sku_fish_002', '20100101', 26);

   
-- uat_sb1
-- fruits
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 30,
   1, 'sku_fruit_001', '20100101', 30);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 30,
   1, 'sku_fruit_002', '20100101', 30);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 30,
   1, 'sku_fruit_003', '20100101', 30);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 30,
   1, 'sku_fruit_004', '20100101', 30);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 30,
   1, 'sku_fruit_005', '20100101', 30);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 30,
   1, 'sku_fruit_006', '20100101', 30);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 30,
   1, 'sku_fruit_007', '20100101', 30);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 30,
   1, 'sku_fruit_008', '20100101', 30);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 30,
   1, 'sku_fruit_009', '20100101', 30);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 30,
   1, 'sku_fruit_010', '20100101', 30);

-- uat_sb2
-- vegetables
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 31,
   2, 'sku_vege_001', '20100101', 31);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 31,
   2, 'sku_vege_002', '20100101', 31);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 31,
   2, 'sku_vege_003', '20100101', 31);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 31,
   2, 'sku_vege_004', '20100101', 31);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 31,
   2, 'sku_vege_005', '20100101', 31);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 31,
   2, 'sku_vege_006', '20100101', 31);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 31,
   2, 'sku_vege_007', '20100101', 31);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 31,
   2, 'sku_vege_008', '20100101', 31);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 31,
   2, 'sku_vege_009', '20100101', 31);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 31,
   2, 'sku_vege_010', '20100101', 31);

--uat_sb3
-- fishes
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 32,
   3, 'sku_fish_001', '20100101', 32);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 32,
   3, 'sku_fish_002', '20100101', 32);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 32,
   3, 'sku_fish_003', '20100101', 32);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 32,
   3, 'sku_fish_004', '20100101', 32);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 32,
   3, 'sku_fish_005', '20100101', 32);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 32,
   3, 'sku_fish_006', '20100101', 32);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 32,
   3, 'sku_fish_007', '20100101', 32);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 32,
   3, 'sku_fish_008', '20100101', 32);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 32,
   3, 'sku_fish_009', '20100101', 32);
INSERT INTO EON_SKU_GROUP
   (SKU_GROUP_ID, ORIG_SKU_GROUP_ID, SELLER_ID, 
   SKU_CATEGORY_ID, DESCRIPTION, START_DATE, CREATED_BY)
 VALUES
   (EON_SKU_GROUP_ID_SEQ.NEXTVAL, EON_SKU_GROUP_ID_SEQ.CURRVAL, 32,
   3, 'sku_fish_010', '20100101', 32);
COMMIT;
COMMIT;