INSERT INTO EON_ORDER
   (ORDER_ID, SELLER_ID, BUYER_ID, 
   DELIVERY_DATE, ORDER_SAVED_BY, CREATED_BY)
 VALUES
   (EON_ORDER_ID_SEQ.NEXTVAL, 2, 14, '20100101', 2, 2);
INSERT INTO EON_ORDER
   (ORDER_ID, SELLER_ID, BUYER_ID, 
   DELIVERY_DATE, ORDER_SAVED_BY, CREATED_BY)
 VALUES
   (EON_ORDER_ID_SEQ.NEXTVAL, 2, 15, '20100101', 2, 2);
INSERT INTO EON_ORDER
   (ORDER_ID, SELLER_ID, BUYER_ID, 
   DELIVERY_DATE, ORDER_SAVED_BY, CREATED_BY)
 VALUES
   (EON_ORDER_ID_SEQ.NEXTVAL, 2, 16, '20100101', 2, 2);
INSERT INTO EON_ORDER
   (ORDER_ID, SELLER_ID, BUYER_ID, 
   DELIVERY_DATE, ORDER_SAVED_BY, CREATED_BY)
 VALUES
   (EON_ORDER_ID_SEQ.NEXTVAL, 2, 19, '20100101', 2, 2);
INSERT INTO EON_ORDER
   (ORDER_ID, SELLER_ID, BUYER_ID, 
   DELIVERY_DATE, ORDER_SAVED_BY, CREATED_BY)
 VALUES
   (EON_ORDER_ID_SEQ.NEXTVAL, 2, 20, '20100101', 2, 2);
INSERT INTO EON_ORDER
   (ORDER_ID, SELLER_ID, BUYER_ID, 
   DELIVERY_DATE, ORDER_SAVED_BY, CREATED_BY)
 VALUES
   (EON_ORDER_ID_SEQ.NEXTVAL, 2, 21, '20100101', 2, 2);
INSERT INTO EON_ORDER
   (ORDER_ID, SELLER_ID, BUYER_ID, 
   DELIVERY_DATE, ORDER_SAVED_BY, CREATED_BY)
 VALUES
   (EON_ORDER_ID_SEQ.NEXTVAL, 3, 14, '20100101', 3, 3);
INSERT INTO EON_ORDER
   (ORDER_ID, SELLER_ID, BUYER_ID, 
   DELIVERY_DATE, ORDER_SAVED_BY, CREATED_BY)
 VALUES
   (EON_ORDER_ID_SEQ.NEXTVAL, 3, 15, '20100101', 3, 3);
INSERT INTO EON_ORDER
   (ORDER_ID, SELLER_ID, BUYER_ID, 
   DELIVERY_DATE, ORDER_SAVED_BY, CREATED_BY)
 VALUES
   (EON_ORDER_ID_SEQ.NEXTVAL, 3, 19, '20100101', 3, 3);
INSERT INTO EON_ORDER
   (ORDER_ID, SELLER_ID, BUYER_ID, 
   DELIVERY_DATE, ORDER_SAVED_BY, CREATED_BY)
 VALUES
   (EON_ORDER_ID_SEQ.NEXTVAL, 3, 20, '20100101', 3, 3);
INSERT INTO EON_ORDER
   (ORDER_ID, SELLER_ID, BUYER_ID, 
   DELIVERY_DATE, ORDER_SAVED_BY, CREATED_BY)
 VALUES
   (EON_ORDER_ID_SEQ.NEXTVAL, 4, 14, '20100101', 4, 4);
INSERT INTO EON_ORDER
   (ORDER_ID, SELLER_ID, BUYER_ID, 
   DELIVERY_DATE, ORDER_SAVED_BY, CREATED_BY)
 VALUES
   (EON_ORDER_ID_SEQ.NEXTVAL, 4, 19, '20100101', 4, 4);
INSERT INTO EON_ORDER
   (ORDER_ID, SELLER_ID, BUYER_ID, 
   DELIVERY_DATE, ORDER_SAVED_BY, CREATED_BY)
 VALUES
   (EON_ORDER_ID_SEQ.NEXTVAL, 8, 14, '20100101', 8, 8);
INSERT INTO EON_ORDER
   (ORDER_ID, SELLER_ID, BUYER_ID, 
   DELIVERY_DATE, ORDER_SAVED_BY, CREATED_BY)
 VALUES
   (EON_ORDER_ID_SEQ.NEXTVAL, 8, 15, '20100101', 8, 8);
INSERT INTO EON_ORDER
   (ORDER_ID, SELLER_ID, BUYER_ID, 
   DELIVERY_DATE, ORDER_SAVED_BY, CREATED_BY)
 VALUES
   (EON_ORDER_ID_SEQ.NEXTVAL, 8, 16, '20100101', 8, 8);
INSERT INTO EON_ORDER
   (ORDER_ID, SELLER_ID, BUYER_ID, 
   DELIVERY_DATE, ORDER_SAVED_BY, CREATED_BY)
 VALUES
   (EON_ORDER_ID_SEQ.NEXTVAL, 9, 19, '20100101', 9, 9);
INSERT INTO EON_ORDER
   (ORDER_ID, SELLER_ID, BUYER_ID, 
   DELIVERY_DATE, ORDER_SAVED_BY, CREATED_BY)
 VALUES
   (EON_ORDER_ID_SEQ.NEXTVAL, 9, 20, '20100101', 9, 9);
INSERT INTO EON_ORDER
   (ORDER_ID, SELLER_ID, BUYER_ID, 
   DELIVERY_DATE, ORDER_SAVED_BY, CREATED_BY)
 VALUES
   (EON_ORDER_ID_SEQ.NEXTVAL, 10, 19, '20100101', 10, 10);
   
-- UAT

INSERT INTO EON_ORDER
   (ORDER_ID, SELLER_ID, BUYER_ID, 
   DELIVERY_DATE, ORDER_SAVED_BY, CREATED_BY)
 VALUES
   (EON_ORDER_ID_SEQ.NEXTVAL, 24, 36, '20100101', 24, 24);
INSERT INTO EON_ORDER
   (ORDER_ID, SELLER_ID, BUYER_ID, 
   DELIVERY_DATE, ORDER_SAVED_BY, CREATED_BY)
 VALUES
   (EON_ORDER_ID_SEQ.NEXTVAL, 24, 37, '20100101', 24, 24);
INSERT INTO EON_ORDER
   (ORDER_ID, SELLER_ID, BUYER_ID, 
   DELIVERY_DATE, ORDER_SAVED_BY, CREATED_BY)
 VALUES
   (EON_ORDER_ID_SEQ.NEXTVAL, 24, 38, '20100101', 24, 24);
INSERT INTO EON_ORDER
   (ORDER_ID, SELLER_ID, BUYER_ID, 
   DELIVERY_DATE, ORDER_SAVED_BY, CREATED_BY)
 VALUES
   (EON_ORDER_ID_SEQ.NEXTVAL, 24, 41, '20100101', 24, 24);
INSERT INTO EON_ORDER
   (ORDER_ID, SELLER_ID, BUYER_ID, 
   DELIVERY_DATE, ORDER_SAVED_BY, CREATED_BY)
 VALUES
   (EON_ORDER_ID_SEQ.NEXTVAL, 24, 42, '20100101', 24, 24);
INSERT INTO EON_ORDER
   (ORDER_ID, SELLER_ID, BUYER_ID, 
   DELIVERY_DATE, ORDER_SAVED_BY, CREATED_BY)
 VALUES
   (EON_ORDER_ID_SEQ.NEXTVAL, 24, 43, '20100101', 24, 24);
INSERT INTO EON_ORDER
   (ORDER_ID, SELLER_ID, BUYER_ID, 
   DELIVERY_DATE, ORDER_SAVED_BY, CREATED_BY)
 VALUES
   (EON_ORDER_ID_SEQ.NEXTVAL, 25, 36, '20100101', 25, 25);
INSERT INTO EON_ORDER
   (ORDER_ID, SELLER_ID, BUYER_ID, 
   DELIVERY_DATE, ORDER_SAVED_BY, CREATED_BY)
 VALUES
   (EON_ORDER_ID_SEQ.NEXTVAL, 25, 37, '20100101', 25, 25);
INSERT INTO EON_ORDER
   (ORDER_ID, SELLER_ID, BUYER_ID, 
   DELIVERY_DATE, ORDER_SAVED_BY, CREATED_BY)
 VALUES
   (EON_ORDER_ID_SEQ.NEXTVAL, 25, 41, '20100101', 25, 25);
INSERT INTO EON_ORDER
   (ORDER_ID, SELLER_ID, BUYER_ID, 
   DELIVERY_DATE, ORDER_SAVED_BY, CREATED_BY)
 VALUES
   (EON_ORDER_ID_SEQ.NEXTVAL, 25, 42, '20100101', 25, 25);
INSERT INTO EON_ORDER
   (ORDER_ID, SELLER_ID, BUYER_ID, 
   DELIVERY_DATE, ORDER_SAVED_BY, CREATED_BY)
 VALUES
   (EON_ORDER_ID_SEQ.NEXTVAL, 26, 36, '20100101', 26, 26);
INSERT INTO EON_ORDER
   (ORDER_ID, SELLER_ID, BUYER_ID, 
   DELIVERY_DATE, ORDER_SAVED_BY, CREATED_BY)
 VALUES
   (EON_ORDER_ID_SEQ.NEXTVAL, 26, 41, '20100101', 26, 26);
INSERT INTO EON_ORDER
   (ORDER_ID, SELLER_ID, BUYER_ID, 
   DELIVERY_DATE, ORDER_SAVED_BY, CREATED_BY)
 VALUES
   (EON_ORDER_ID_SEQ.NEXTVAL, 30, 41, '20100101', 30, 30);
INSERT INTO EON_ORDER
   (ORDER_ID, SELLER_ID, BUYER_ID, 
   DELIVERY_DATE, ORDER_SAVED_BY, CREATED_BY)
 VALUES
   (EON_ORDER_ID_SEQ.NEXTVAL, 30, 42, '20100101', 30, 30);
INSERT INTO EON_ORDER
   (ORDER_ID, SELLER_ID, BUYER_ID, 
   DELIVERY_DATE, ORDER_SAVED_BY, CREATED_BY)
 VALUES
   (EON_ORDER_ID_SEQ.NEXTVAL, 30, 43, '20100101', 30, 30);
INSERT INTO EON_ORDER
   (ORDER_ID, SELLER_ID, BUYER_ID, 
   DELIVERY_DATE, ORDER_SAVED_BY, CREATED_BY)
 VALUES
   (EON_ORDER_ID_SEQ.NEXTVAL, 31, 41, '20100101', 31, 31);
INSERT INTO EON_ORDER
   (ORDER_ID, SELLER_ID, BUYER_ID, 
   DELIVERY_DATE, ORDER_SAVED_BY, CREATED_BY)
 VALUES
   (EON_ORDER_ID_SEQ.NEXTVAL, 31, 42, '20100101', 31, 31);
INSERT INTO EON_ORDER
   (ORDER_ID, SELLER_ID, BUYER_ID, 
   DELIVERY_DATE, ORDER_SAVED_BY, CREATED_BY)
 VALUES
   (EON_ORDER_ID_SEQ.NEXTVAL, 32, 41, '20100101', 32,  32);