-- uat_sa2 / 25
-- uat_ba1 / 36
-- order_id = 25

-- uat_sa2 / 25
-- uat_ba2 / 37
-- order_id = 26

-- uat_sa2 / 25
-- uat_bb1 / 41
-- order_id = 27

-- uat_sa2 / 25
-- uat_bb2 / 42
-- order_id = 28

INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 25, 861, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 26, 861, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 27, 861, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 28, 861, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 25, 862, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 26, 862, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 27, 862, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 28, 862, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 25, 863, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 26, 863, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 27, 863, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 28, 863, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 25, 864, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 26, 864, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 27, 864, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 28, 864, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 25, 865, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 26, 865, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 27, 865, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 28, 865, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 25, 866, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 26, 866, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 27, 866, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 28, 866, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 25, 867, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 26, 867, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 27, 867, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 28, 867, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 25, 868, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 26, 868, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 27, 868, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 28, 868, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 25, 869, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 26, 869, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 27, 869, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 28, 869, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 25, 870, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 26, 870, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 27, 870, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 28, 870, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 25, 871, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 26, 871, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 27, 871, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 28, 871, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 25, 872, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 26, 872, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 27, 872, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 28, 872, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 25, 873, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 26, 873, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 27, 873, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 28, 873, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 25, 874, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 26, 874, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 27, 874, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 28, 874, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 25, 875, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 26, 875, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 27, 875, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 28, 875, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 25, 876, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 26, 876, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 27, 876, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 28, 876, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 25, 877, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 26, 877, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 27, 877, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 28, 877, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 25, 878, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 26, 878, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 27, 878, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 28, 878, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 25, 879, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 26, 879, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 27, 879, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 28, 879, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 25, 880, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 26, 880, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 27, 880, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 28, 880, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 25, 881, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 26, 881, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 27, 881, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 28, 881, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 25, 882, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 26, 882, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 27, 882, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 28, 882, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 25, 883, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 26, 883, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 27, 883, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 28, 883, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 25, 884, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 26, 884, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 27, 884, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 28, 884, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 25, 885, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 26, 885, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 27, 885, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 28, 885, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 25, 886, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 26, 886, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 27, 886, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 28, 886, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 25, 887, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 26, 887, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 27, 887, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 28, 887, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 25, 888, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 26, 888, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 27, 888, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 28, 888, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 25, 889, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 26, 889, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 27, 889, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 28, 889, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 25, 890, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 26, 890, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 27, 890, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 28, 890, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 25, 891, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 26, 891, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 27, 891, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 28, 891, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 25, 892, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 26, 892, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 27, 892, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 28, 892, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 25, 893, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 26, 893, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 27, 893, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 28, 893, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 25, 894, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 26, 894, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 27, 894, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 28, 894, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 25, 895, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 26, 895, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 27, 895, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 28, 895, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 25, 896, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 26, 896, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 27, 896, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 28, 896, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 25, 897, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 26, 897, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 27, 897, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 28, 897, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 25, 898, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 26, 898, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 27, 898, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 28, 898, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 25, 899, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 26, 899, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 27, 899, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 28, 899, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 25, 900, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 26, 900, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 27, 900, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 28, 900, 5, '1', '1'); 

COMMIT;