-- s_ca01
-- b_ca01
-- fruits
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 1, 1, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 1, 2, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 1, 3, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 1, 4, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 1, 5, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 1, 6, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 1, 7, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 1, 8, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 1, 9, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 1, 10, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 1, 11, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 1, 12, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 1, 13, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 1, 14, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 1, 15, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 1, 16, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 1, 17, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 1, 18, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 1, 19, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 1, 20, 5, '1', '1');
-- vegetables
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 1, 21, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 1, 22, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 1, 23, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 1, 24, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 1, 25, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 1, 26, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 1, 27, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 1, 28, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 1, 29, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 1, 30, 5, '1', '1');
-- fish
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 1, 31, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 1, 32, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 1, 33, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 1, 34, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 1, 35, 5, '1', '1');

-- s_ca01
-- b_ca02
-- fruits
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 2, 1, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 2, 2, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 2, 3, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 2, 4, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 2, 5, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 2, 6, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 2, 7, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 2, 8, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 2, 9, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 2, 10, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 2, 11, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 2, 12, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 2, 13, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 2, 14, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 2, 15, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 2, 16, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 2, 17, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 2, 18, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 2, 19, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 2, 20, 5, '1', '1');
-- vegetables
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 2, 21, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 2, 22, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 2, 23, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 2, 24, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 2, 25, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 2, 26, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 2, 27, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 2, 28, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 2, 29, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 2, 30, 5, '1', '1');
-- fish
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 2, 31, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 2, 32, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 2, 33, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 2, 34, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 2, 35, 5, '1', '1');
 	
-- s_ca01
-- b_ca03
-- fruits
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 3, 1, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 3, 2, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 3, 3, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 3, 4, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 3, 5, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 3, 6, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 3, 7, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 3, 8, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 3, 9, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 3, 10, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 3, 11, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 3, 12, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 3, 13, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 3, 14, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 3, 15, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 3, 16, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 3, 17, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 3, 18, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 3, 19, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 3, 20, 5, '1', '1');
-- vegetables
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 3, 21, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 3, 22, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 3, 23, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 3, 24, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 3, 25, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 3, 26, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 3, 27, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 3, 28, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 3, 29, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 3, 30, 5, '1', '1');
-- fish
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 3, 31, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 3, 32, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 3, 33, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 3, 34, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 3, 35, 5, '1', '1');
 	
-- s_ca01
-- b_cb01
-- fruits
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 4, 1, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 4, 2, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 4, 3, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 4, 4, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 4, 5, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 4, 6, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 4, 7, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 4, 8, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 4, 9, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 4, 10, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 4, 11, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 4, 12, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 4, 13, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 4, 14, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 4, 15, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 4, 16, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 4, 17, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 4, 18, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 4, 19, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 4, 20, 5, '1', '1');
-- vegetables
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 4, 21, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 4, 22, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 4, 23, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 4, 24, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 4, 25, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 4, 26, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 4, 27, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 4, 28, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 4, 29, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 4, 30, 5, '1', '1');
-- fish
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 4, 31, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 4, 32, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 4, 33, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 4, 34, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 4, 35, 5, '1', '1');
 	
-- s_ca01
-- b_cb02
-- fruits
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 5, 1, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 5, 2, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 5, 3, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 5, 4, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 5, 5, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 5, 6, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 5, 7, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 5, 8, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 5, 9, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 5, 10, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 5, 11, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 5, 12, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 5, 13, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 5, 14, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 5, 15, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 5, 16, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 5, 17, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 5, 18, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 5, 19, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 5, 20, 5, '1', '1');
-- vegetables
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 5, 21, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 5, 22, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 5, 23, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 5, 24, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 5, 25, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 5, 26, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 5, 27, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 5, 28, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 5, 29, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 5, 30, 5, '1', '1');
-- fish
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 5, 31, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 5, 32, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 5, 33, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 5, 34, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 5, 35, 5, '1', '1');
 	
-- s_ca01
-- b_cb03
-- fruits
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 6, 1, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 6, 2, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 6, 3, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 6, 4, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 6, 5, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 6, 6, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 6, 7, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 6, 8, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 6, 9, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 6, 10, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 6, 11, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 6, 12, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 6, 13, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 6, 14, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 6, 15, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 6, 16, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 6, 17, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 6, 18, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 6, 19, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 6, 20, 5, '1', '1');
-- vegetables
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 6, 21, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 6, 22, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 6, 23, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 6, 24, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 6, 25, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 6, 26, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 6, 27, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 6, 28, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 6, 29, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 6, 30, 5, '1', '1');
-- fish
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 6, 31, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 6, 32, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 6, 33, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 6, 34, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 6, 35, 5, '1', '1');
COMMIT;