-- s_ca01
INSERT INTO EON_USERS_CATEGORY
   (USER_ID, CATEGORY_ID)
 VALUES
   (2,1);
INSERT INTO EON_USERS_CATEGORY
   (USER_ID, CATEGORY_ID)
 VALUES
   (2,2);
INSERT INTO EON_USERS_CATEGORY
   (USER_ID, CATEGORY_ID)
 VALUES
   (2,3);

-- s_ca02
INSERT INTO EON_USERS_CATEGORY
   (USER_ID, CATEGORY_ID)
 VALUES
   (3,1);
INSERT INTO EON_USERS_CATEGORY
   (USER_ID, CATEGORY_ID)
 VALUES
   (3,2);
INSERT INTO EON_USERS_CATEGORY
   (USER_ID, CATEGORY_ID)
 VALUES
   (3,3);
   
-- s_ca03
INSERT INTO EON_USERS_CATEGORY
   (USER_ID, CATEGORY_ID)
 VALUES
   (4,1);
INSERT INTO EON_USERS_CATEGORY
   (USER_ID, CATEGORY_ID)
 VALUES
   (4,2);
INSERT INTO EON_USERS_CATEGORY
   (USER_ID, CATEGORY_ID)
 VALUES
   (4,3);

-- s_cb01
INSERT INTO EON_USERS_CATEGORY
   (USER_ID, CATEGORY_ID)
 VALUES
   (8,1);
   
-- s_cb02
INSERT INTO EON_USERS_CATEGORY
   (USER_ID, CATEGORY_ID)
 VALUES
   (9,2);
   
-- s_cb03
INSERT INTO EON_USERS_CATEGORY
   (USER_ID, CATEGORY_ID)
 VALUES
   (10,3);
COMMIT;

--UAT USERS

-- s_ca01
INSERT INTO EON_USERS_CATEGORY
   (USER_ID, CATEGORY_ID)
 VALUES
   (24,1);
INSERT INTO EON_USERS_CATEGORY
   (USER_ID, CATEGORY_ID)
 VALUES
   (24,2);
INSERT INTO EON_USERS_CATEGORY
   (USER_ID, CATEGORY_ID)
 VALUES
   (24,3);

-- s_ca02
INSERT INTO EON_USERS_CATEGORY
   (USER_ID, CATEGORY_ID)
 VALUES
   (25,1);
INSERT INTO EON_USERS_CATEGORY
   (USER_ID, CATEGORY_ID)
 VALUES
   (25,2);
INSERT INTO EON_USERS_CATEGORY
   (USER_ID, CATEGORY_ID)
 VALUES
   (25,3);
   
-- s_ca03
INSERT INTO EON_USERS_CATEGORY
   (USER_ID, CATEGORY_ID)
 VALUES
   (26,1);
INSERT INTO EON_USERS_CATEGORY
   (USER_ID, CATEGORY_ID)
 VALUES
   (26,2);
INSERT INTO EON_USERS_CATEGORY
   (USER_ID, CATEGORY_ID)
 VALUES
   (26,3);

-- s_cb01
INSERT INTO EON_USERS_CATEGORY
   (USER_ID, CATEGORY_ID)
 VALUES
   (30,1);
   
-- s_cb02
INSERT INTO EON_USERS_CATEGORY
   (USER_ID, CATEGORY_ID)
 VALUES
   (31,2);
   
-- s_cb03
INSERT INTO EON_USERS_CATEGORY
   (USER_ID, CATEGORY_ID)
 VALUES
   (32,3);
COMMIT;