Insert into EON_COMPANY
   (COMPANY_ID, COMPANY_NAME, SHORT_NAME, COMPANY_TYPE_ID, CONTACT_PERSON,
   SOX_FLAG, COMPANY_ADDRESS1, COMPANY_ADDRESS2, COMPANY_ADDRESS3,
   TELEPHONE_NUMBER, EMAIL_ADDRESS, FAX_NUMBER, COMMENTS )
 Values
   (EON_COMPANY_SEQ.NEXTVAL, 'FRC_ADMIN', 'FRC_ADMIN', '1', 'Contact Person',
   0, 'Company Address 1', 'Company Address 2', 'Company Address 3',
   '7527263', 'eon@farmind.com.ph', '7527261', 'Comments');
Insert into EON_COMPANY
   (COMPANY_ID, COMPANY_NAME, SHORT_NAME, COMPANY_TYPE_ID, CONTACT_PERSON,
   SOX_FLAG, COMPANY_ADDRESS1, COMPANY_ADDRESS2, COMPANY_ADDRESS3,
   TELEPHONE_NUMBER, EMAIL_ADDRESS, FAX_NUMBER, COMMENTS )
 Values
   (EON_COMPANY_SEQ.NEXTVAL, 'FRASC_S_CA', 'S_CA', 2, 'Contact Person',
   0, 'Company Address 1', 'Company Address 2', 'Company Address 3',
   '7527263', 'eon@farmind.com.ph', '7527261', 'Comments');
Insert into EON_COMPANY
   (COMPANY_ID, COMPANY_NAME, SHORT_NAME, COMPANY_TYPE_ID, CONTACT_PERSON,
   SOX_FLAG, COMPANY_ADDRESS1, COMPANY_ADDRESS2, COMPANY_ADDRESS3,
   TELEPHONE_NUMBER, EMAIL_ADDRESS, FAX_NUMBER, COMMENTS )
 Values
   (EON_COMPANY_SEQ.NEXTVAL, 'FRASC_S_CB', 'S_CB', 2, 'Contact Person',
   0, 'Company Address 1', 'Company Address 2', 'Company Address 3',
   '7527263', 'eon@farmind.com.ph', '7527261', 'Comments');
Insert into EON_COMPANY
   (COMPANY_ID, COMPANY_NAME, SHORT_NAME, COMPANY_TYPE_ID, CONTACT_PERSON,
   SOX_FLAG, COMPANY_ADDRESS1, COMPANY_ADDRESS2, COMPANY_ADDRESS3,
   TELEPHONE_NUMBER, EMAIL_ADDRESS, FAX_NUMBER, COMMENTS )
 Values
   (EON_COMPANY_SEQ.NEXTVAL, 'FRASC_B_CA', 'B_CA', 3, 'Contact Person',
   0, 'Company Address 1', 'Company Address 2', 'Company Address 3',
   '7527263', 'eon@farmind.com.ph', '7527261', 'Comments');
Insert into EON_COMPANY
   (COMPANY_ID, COMPANY_NAME, SHORT_NAME, COMPANY_TYPE_ID, CONTACT_PERSON,
   SOX_FLAG, COMPANY_ADDRESS1, COMPANY_ADDRESS2, COMPANY_ADDRESS3,
   TELEPHONE_NUMBER, EMAIL_ADDRESS, FAX_NUMBER, COMMENTS )
 Values
   (EON_COMPANY_SEQ.NEXTVAL, 'FRASC_B_CB', 'B_CB', 3, 'Contact Person',
   0, 'Company Address 1', 'Company Address 2', 'Company Address 3',
   '7527263', 'eon@farmind.com.ph', '7527261', 'Comments');
Insert into EON_COMPANY
   (COMPANY_ID, COMPANY_NAME, SHORT_NAME, COMPANY_TYPE_ID, CONTACT_PERSON,
   SOX_FLAG, COMPANY_ADDRESS1, COMPANY_ADDRESS2, COMPANY_ADDRESS3,
   TELEPHONE_NUMBER, EMAIL_ADDRESS, FAX_NUMBER, COMMENTS )
 Values
   (EON_COMPANY_SEQ.NEXTVAL, 'UAT_SA', 'SA', 2, 'Contact Person',
   0, 'Company Address 1', 'Company Address 2', 'Company Address 3',
   '7527263', 'eon@farmind.com.ph', '7527261', 'Comments');
Insert into EON_COMPANY
   (COMPANY_ID, COMPANY_NAME, SHORT_NAME, COMPANY_TYPE_ID, CONTACT_PERSON,
   SOX_FLAG, COMPANY_ADDRESS1, COMPANY_ADDRESS2, COMPANY_ADDRESS3,
   TELEPHONE_NUMBER, EMAIL_ADDRESS, FAX_NUMBER, COMMENTS )
 Values
   (EON_COMPANY_SEQ.NEXTVAL, 'UAT_SB', 'SB', 2, 'Contact Person',
   0, 'Company Address 1', 'Company Address 2', 'Company Address 3',
   '7527263', 'eon@farmind.com.ph', '7527261', 'Comments');
Insert into EON_COMPANY
   (COMPANY_ID, COMPANY_NAME, SHORT_NAME, COMPANY_TYPE_ID, CONTACT_PERSON,
   SOX_FLAG, COMPANY_ADDRESS1, COMPANY_ADDRESS2, COMPANY_ADDRESS3,
   TELEPHONE_NUMBER, EMAIL_ADDRESS, FAX_NUMBER, COMMENTS )
 Values
   (EON_COMPANY_SEQ.NEXTVAL, 'UAT_BA', 'BA', 3, 'Contact Person',
   0, 'Company Address 1', 'Company Address 2', 'Company Address 3',
   '7527263', 'eon@farmind.com.ph', '7527261', 'Comments');
Insert into EON_COMPANY
   (COMPANY_ID, COMPANY_NAME, SHORT_NAME, COMPANY_TYPE_ID, CONTACT_PERSON,
   SOX_FLAG, COMPANY_ADDRESS1, COMPANY_ADDRESS2, COMPANY_ADDRESS3,
   TELEPHONE_NUMBER, EMAIL_ADDRESS, FAX_NUMBER, COMMENTS )
 Values
   (EON_COMPANY_SEQ.NEXTVAL, 'UAT_BB', 'BB', 3, 'Contact Person',
   0, 'Company Address 1', 'Company Address 2', 'Company Address 3',
   '7527263', 'eon@farmind.com.ph', '7527261', 'Comments');
COMMIT;
