-- uat_sb2 / 31
-- uat_bb1 / 41
-- order_id = 34

-- uat_sb2 / 31
-- uat_bb2 / 42
-- order_id = 35

INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 34, 1611, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 35, 1611, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 34, 1612, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 35, 1612, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 34, 1613, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 35, 1613, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 34, 1614, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 35, 1614, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 34, 1615, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 35, 1615, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 34, 1616, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 35, 1616, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 34, 1617, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 35, 1617, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 34, 1618, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 35, 1618, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 34, 1619, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 35, 1619, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 34, 1620, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 35, 1620, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 34, 1621, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 35, 1621, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 34, 1622, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 35, 1622, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 34, 1623, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 35, 1623, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 34, 1624, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 35, 1624, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 34, 1625, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 35, 1625, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 34, 1626, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 35, 1626, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 34, 1627, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 35, 1627, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 34, 1628, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 35, 1628, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 34, 1629, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 35, 1629, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 34, 1630, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 35, 1630, 5, '1', '1'); 


COMMIT;