INSERT INTO EON_PRODUCT_MASTER_FILE
   (PROD_MASTER_ID, USER_ID, NAME)
 VALUES
   (EON_PRODUCT_MASTER_FILE_SEQ.NEXTVAL, 2, 'FRC Master File');
INSERT INTO EON_PRODUCT_MASTER_FILE
   (PROD_MASTER_ID, USER_ID, NAME)
 VALUES
   (EON_PRODUCT_MASTER_FILE_SEQ.NEXTVAL, 3, 'FRC Master File');
INSERT INTO EON_PRODUCT_MASTER_FILE
   (PROD_MASTER_ID, USER_ID, NAME)
 VALUES
   (EON_PRODUCT_MASTER_FILE_SEQ.NEXTVAL, 4, 'FRC Master File');
INSERT INTO EON_PRODUCT_MASTER_FILE
   (PROD_MASTER_ID, USER_ID, NAME)
 VALUES
   (EON_PRODUCT_MASTER_FILE_SEQ.NEXTVAL, 8, 'FRC Master File');
INSERT INTO EON_PRODUCT_MASTER_FILE
   (PROD_MASTER_ID, USER_ID, NAME)
 VALUES
   (EON_PRODUCT_MASTER_FILE_SEQ.NEXTVAL, 9, 'FRC Master File');
INSERT INTO EON_PRODUCT_MASTER_FILE
   (PROD_MASTER_ID, USER_ID, NAME)
 VALUES
   (EON_PRODUCT_MASTER_FILE_SEQ.NEXTVAL, 10, 'FRC Master File');
   
-- UAT
INSERT INTO EON_PRODUCT_MASTER_FILE
   (PROD_MASTER_ID, USER_ID, NAME)
 VALUES
   (EON_PRODUCT_MASTER_FILE_SEQ.NEXTVAL, 24, 'FRC Master File');
INSERT INTO EON_PRODUCT_MASTER_FILE
   (PROD_MASTER_ID, USER_ID, NAME)
 VALUES
   (EON_PRODUCT_MASTER_FILE_SEQ.NEXTVAL, 25, 'FRC Master File');
INSERT INTO EON_PRODUCT_MASTER_FILE
   (PROD_MASTER_ID, USER_ID, NAME)
 VALUES
   (EON_PRODUCT_MASTER_FILE_SEQ.NEXTVAL, 26, 'FRC Master File');
INSERT INTO EON_PRODUCT_MASTER_FILE
   (PROD_MASTER_ID, USER_ID, NAME)
 VALUES
   (EON_PRODUCT_MASTER_FILE_SEQ.NEXTVAL, 30, 'FRC Master File');
INSERT INTO EON_PRODUCT_MASTER_FILE
   (PROD_MASTER_ID, USER_ID, NAME)
 VALUES
   (EON_PRODUCT_MASTER_FILE_SEQ.NEXTVAL, 31, 'FRC Master File');
INSERT INTO EON_PRODUCT_MASTER_FILE
   (PROD_MASTER_ID, USER_ID, NAME)
 VALUES
   (EON_PRODUCT_MASTER_FILE_SEQ.NEXTVAL, 32, 'FRC Master File');
COMMIT;
