-- order id = 16
-- s_cb02
-- b_cb01
-- vegetables
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 16, 786, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 16, 787, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 16, 788, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 16, 789, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 16, 790, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 16, 791, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 16, 792, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 16, 793, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 16, 794, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 16, 795, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 16, 796, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 16, 797, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 16, 798, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 16, 799, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 16, 800, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 16, 801, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 16, 802, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 16, 803, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 16, 804, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 16, 805, 5, '1', '1');

-- order id = 17
-- s_cb02
-- b_cb02
-- vegetables
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 17, 786, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 17, 787, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 17, 788, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 17, 789, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 17, 790, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 17, 791, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 17, 792, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 17, 793, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 17, 794, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 17, 795, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 17, 796, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 17, 797, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 17, 798, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 17, 799, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 17, 800, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 17, 801, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 17, 802, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 17, 803, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 17, 804, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 17, 805, 5, '1', '1');
COMMIT;