-- uat_sb3 / 32
-- fish / 3
-- piece / 5
-- sku_fish_001 / 159
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 32,
   159, 5, 10001, 3,
   'TestdataFish001', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 32);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 32,
   159, 5, 10001, 3,
   'TestdataFish002', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 32);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 32,
   159, 5, 10001, 3,
   'TestdataFish003', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 32);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 32,
   159, 5, 10001, 3,
   'TestdataFish004', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 32);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 32,
   159, 5, 10001, 3,
   'TestdataFish005', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 32);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 32,
   159, 5, 10001, 3,
   'TestdataFish006', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 32);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 32,
   159, 5, 10001, 3,
   'TestdataFish007', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 32);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 32,
   159, 5, 10001, 3,
   'TestdataFish008', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 32);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 32,
   159, 5, 10001, 3,
   'TestdataFish009', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 32);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 32,
   159, 5, 10001, 3,
   'TestdataFish010', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 32);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 32,
   159, 5, 10001, 3,
   'TestdataFish011', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 32);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 32,
   159, 5, 10001, 3,
   'TestdataFish012', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 32);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 32,
   159, 5, 10001, 3,
   'TestdataFish013', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 32);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 32,
   159, 5, 10001, 3,
   'TestdataFish014', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 32);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 32,
   159, 5, 10001, 3,
   'TestdataFish015', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 32);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 32,
   159, 5, 10001, 3,
   'TestdataFish016', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 32);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 32,
   159, 5, 10001, 3,
   'TestdataFish017', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 32);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 32,
   159, 5, 10001, 3,
   'TestdataFish018', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 32);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 32,
   159, 5, 10001, 3,
   'TestdataFish019', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 32);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 32,
   159, 5, 10001, 3,
   'TestdataFish020', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 32);
COMMIT;