-- uat_sa1 / 24
-- uat_ba1 / 36
-- order_id = 19

-- uat_sa1 / 24
-- uat_ba2 / 37
-- order_id = 20

-- uat_sa1 / 24
-- uat_ba3 / 38
-- order_id = 21

-- uat_sa1 / 24
-- uat_bb1 / 41
-- order_id = 22

-- uat_sa1 / 24
-- uat_bb2 / 42
-- order_id = 23

-- uat_sa1 / 24
-- uat_bb3 / 43
-- order_id = 24

INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 19, 826, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 20, 826, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 21, 826, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 22, 826, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 23, 826, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 24, 826, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 19, 827, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 20, 827, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 21, 827, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 22, 827, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 23, 827, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 24, 827, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 19, 828, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 20, 828, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 21, 828, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 22, 828, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 23, 828, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 24, 828, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 19, 829, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 20, 829, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 21, 829, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 22, 829, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 23, 829, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 24, 829, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 19, 830, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 20, 830, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 21, 830, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 22, 830, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 23, 830, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 24, 830, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 19, 831, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 20, 831, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 21, 831, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 22, 831, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 23, 831, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 24, 831, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 19, 832, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 20, 832, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 21, 832, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 22, 832, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 23, 832, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 24, 832, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 19, 833, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 20, 833, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 21, 833, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 22, 833, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 23, 833, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 24, 833, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 19, 834, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 20, 834, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 21, 834, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 22, 834, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 23, 834, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 24, 834, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 19, 835, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 20, 835, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 21, 835, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 22, 835, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 23, 835, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 24, 835, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 19, 836, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 20, 836, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 21, 836, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 22, 836, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 23, 836, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 24, 836, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 19, 837, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 20, 837, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 21, 837, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 22, 837, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 23, 837, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 24, 837, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 19, 838, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 20, 838, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 21, 838, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 22, 838, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 23, 838, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 24, 838, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 19, 839, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 20, 839, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 21, 839, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 22, 839, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 23, 839, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 24, 839, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 19, 840, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 20, 840, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 21, 840, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 22, 840, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 23, 840, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 24, 840, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 19, 841, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 20, 841, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 21, 841, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 22, 841, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 23, 841, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 24, 841, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 19, 842, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 20, 842, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 21, 842, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 22, 842, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 23, 842, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 24, 842, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 19, 843, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 20, 843, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 21, 843, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 22, 843, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 23, 843, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 24, 843, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 19, 844, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 20, 844, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 21, 844, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 22, 844, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 23, 844, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 24, 844, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 19, 845, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 20, 845, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 21, 845, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 22, 845, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 23, 845, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 24, 845, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 19, 846, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 20, 846, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 21, 846, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 22, 846, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 23, 846, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 24, 846, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 19, 847, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 20, 847, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 21, 847, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 22, 847, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 23, 847, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 24, 847, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 19, 848, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 20, 848, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 21, 848, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 22, 848, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 23, 848, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 24, 848, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 19, 849, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 20, 849, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 21, 849, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 22, 849, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 23, 849, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 24, 849, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 19, 850, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 20, 850, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 21, 850, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 22, 850, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 23, 850, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 24, 850, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 19, 851, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 20, 851, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 21, 851, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 22, 851, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 23, 851, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 24, 851, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 19, 852, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 20, 852, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 21, 852, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 22, 852, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 23, 852, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 24, 852, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 19, 853, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 20, 853, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 21, 853, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 22, 853, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 23, 853, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 24, 853, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 19, 854, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 20, 854, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 21, 854, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 22, 854, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 23, 854, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 24, 854, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 19, 855, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 20, 855, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 21, 855, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 22, 855, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 23, 855, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 24, 855, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 19, 856, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 20, 856, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 21, 856, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 22, 856, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 23, 856, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 24, 856, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 19, 857, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 20, 857, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 21, 857, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 22, 857, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 23, 857, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 24, 857, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 19, 858, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 20, 858, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 21, 858, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 22, 858, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 23, 858, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 24, 858, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 19, 859, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 20, 859, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 21, 859, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 22, 859, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 23, 859, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 24, 859, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 19, 860, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 20, 860, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 21, 860, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 22, 860, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 23, 860, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 24, 860, 5, '1', '1'); 
COMMIT;