-- uat_sb2 / 31
-- vegetables / 2
-- piece / 3
-- sku_vege_001 / 149
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 31,
   149, 3, 10001, 2,
   'TestDataVege001', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 31);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 31,
   149, 3, 10001, 2,
   'TestDataVege002', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 31);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 31,
   149, 3, 10001, 2,
   'TestDataVege003', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 31);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 31,
   149, 3, 10001, 2,
   'TestDataVege004', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 31);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 31,
   149, 3, 10001, 2,
   'TestDataVege005', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 31);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 31,
   149, 3, 10001, 2,
   'TestDataVege006', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 31);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 31,
   149, 3, 10001, 2,
   'TestDataVege007', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 31);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 31,
   149, 3, 10001, 2,
   'TestDataVege008', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 31);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 31,
   149, 3, 10001, 2,
   'TestDataVege009', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 31);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 31,
   149, 3, 10001, 2,
   'TestDataVege010', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 31);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 31,
   149, 3, 10001, 2,
   'TestDataVege011', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 31);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 31,
   149, 3, 10001, 2,
   'TestDataVege012', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 31);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 31,
   149, 3, 10001, 2,
   'TestDataVege013', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 31);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 31,
   149, 3, 10001, 2,
   'TestDataVege014', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 31);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 31,
   149, 3, 10001, 2,
   'TestDataVege015', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 31);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 31,
   149, 3, 10001, 2,
   'TestDataVege016', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 31);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 31,
   149, 3, 10001, 2,
   'TestDataVege017', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 31);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 31,
   149, 3, 10001, 2,
   'TestDataVege018', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 31);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 31,
   149, 3, 10001, 2,
   'TestDataVege019', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 31);
INSERT INTO EON_SKU
   (SKU_ID, ORIGINAL_SKU_ID, SELLER_ID, 
   SKU_GROUP_ID, ORDER_UNIT_ID, SHEET_TYPE_ID, SKU_CATEGORY_ID,
   SKU_NAME, LOCATION, MARKET, GRADE, CLASS,
   PRICE1, PRICE2, PRICE_WITHOUT_TAX, PACKAGE_QUANTITY,
   PACKAGE_TYPE, CREATED_BY)
 VALUES
   (EON_SKU_ID_SEQ.NEXTVAL, EON_SKU_ID_SEQ.CURRVAL, 31,
   149, 3, 10001, 2,
   'TestDataVege020', 'Location', 'Market', 'Grade', 'Class', 
   200, 250, 150, 10, 
   'Package Type', 31);
COMMIT;