-- uat_sb3 / 32
-- uat_bb1 / 41
-- order_id = 36

INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 36, 1631, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 36, 1632, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 36, 1633, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 36, 1634, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 36, 1635, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 36, 1636, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 36, 1637, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 36, 1638, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 36, 1639, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 36, 1640, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 36, 1641, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 36, 1642, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 36, 1643, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 36, 1644, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 36, 1645, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 36, 1646, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 36, 1647, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 36, 1648, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 36, 1649, 5, '1', '1'); 
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG) 
		VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 36, 1650, 5, '1', '1'); 


COMMIT;