-- order id = 18
-- s_cb03
-- b_cb01
-- fish
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 18, 806, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 18, 807, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 18, 808, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 18, 809, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 18, 810, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 18, 811, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 18, 812, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 18, 813, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 18, 814, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 18, 815, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 18, 816, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 18, 817, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 18, 818, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 18, 819, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 18, 820, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 18, 821, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 18, 822, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 18, 823, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 18, 824, 5, '1', '1');
INSERT INTO EON_ORDER_ITEM (ORDER_ITEM_ID, ORDER_ID, SKU_ID, QUANTITY, SOS_VIS_FLAG, BAOS_VIS_FLAG)
 	VALUES (EON_ORDER_ITEM_SEQ.NEXTVAL, 18, 825, 5, '1', '1');
COMMIT;