--------------------------------------------------------
--  EON_USERS_TOS to add the TOS details
--  FLAG : default 0; 1=agree; 0=disagree
--  FLAG_SET_BY : username who set the flag
--  FLAG_DATE : Date when flag was set
--------------------------------------------------------
CREATE TABLE EON_USERS_TOS 
(
    VERSION NUMBER DEFAULT 1 NOT NULL,
    USER_ID NUMBER(9) NOT NULL, 
    FLAG VARCHAR2(1) DEFAULT '0' NOT NULL,
    FLAG_SET_BY VARCHAR2(32) NOT NULL,
    FLAG_DATE TIMESTAMP NOT NULL 
)
TABLESPACE EON_DATA1 LOGGING 
    NOCOMPRESS 
    NOCACHE
    NOPARALLEL
    MONITORING;

ALTER TABLE EON_USERS_TOS ADD CONSTRAINT EON_USERS_TOS_PK PRIMARY KEY (USER_ID);

ALTER TABLE EON_USERS_TOS ADD CONSTRAINT EON_USERS_TOS_FK1 FOREIGN KEY (USER_ID)
REFERENCES EON_USERS (USER_ID) ENABLE;

ALTER TABLE EON_USERS_TOS ADD CONSTRAINT EON_USERS_TOS_FK2 FOREIGN KEY (FLAG_SET_BY)
REFERENCES EON_USERS (USERNAME) ENABLE;
    
