-------------------------------------------------------
--  Constraints for Table ALLOC_RCVD_DIFF_QTY_ERROR_MST
--------------------------------------------------------

  ALTER TABLE ALLOC_RCVD_DIFF_QTY_ERROR_MST MODIFY (RCVD_SKU_CNT NOT NULL ENABLE);
  ALTER TABLE ALLOC_RCVD_DIFF_QTY_ERROR_MST MODIFY (RCVD_ORDER_ID NOT NULL ENABLE);
  ALTER TABLE ALLOC_RCVD_DIFF_QTY_ERROR_MST MODIFY (ALLOC_SKU_CNT NOT NULL ENABLE);
  ALTER TABLE ALLOC_RCVD_DIFF_QTY_ERROR_MST MODIFY (DELIVERY_DATE NOT NULL ENABLE);
  ALTER TABLE ALLOC_RCVD_DIFF_QTY_ERROR_MST MODIFY (NAME NOT NULL ENABLE);
  ALTER TABLE ALLOC_RCVD_DIFF_QTY_ERROR_MST MODIFY (PASS NOT NULL ENABLE);
  ALTER TABLE ALLOC_RCVD_DIFF_QTY_ERROR_MST MODIFY (USERNAME NOT NULL ENABLE);
  ALTER TABLE ALLOC_RCVD_DIFF_QTY_ERROR_MST MODIFY (SELLER_ID NOT NULL ENABLE);
  ALTER TABLE ALLOC_RCVD_DIFF_QTY_ERROR_MST MODIFY (ALLOC_ORDER_ID NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ALLOC_RCVD_DIFF_QTY_ERROR_TMP
--------------------------------------------------------

  ALTER TABLE ALLOC_RCVD_DIFF_QTY_ERROR_TMP MODIFY (RCVD_SKU_CNT NOT NULL ENABLE);
  ALTER TABLE ALLOC_RCVD_DIFF_QTY_ERROR_TMP MODIFY (RCVD_ORDER_ID NOT NULL ENABLE);
  ALTER TABLE ALLOC_RCVD_DIFF_QTY_ERROR_TMP MODIFY (ALLOC_SKU_CNT NOT NULL ENABLE);
  ALTER TABLE ALLOC_RCVD_DIFF_QTY_ERROR_TMP MODIFY (DELIVERY_DATE NOT NULL ENABLE);
  ALTER TABLE ALLOC_RCVD_DIFF_QTY_ERROR_TMP MODIFY (NAME NOT NULL ENABLE);
  ALTER TABLE ALLOC_RCVD_DIFF_QTY_ERROR_TMP MODIFY (PASS NOT NULL ENABLE);
  ALTER TABLE ALLOC_RCVD_DIFF_QTY_ERROR_TMP MODIFY (USERNAME NOT NULL ENABLE);
  ALTER TABLE ALLOC_RCVD_DIFF_QTY_ERROR_TMP MODIFY (SELLER_ID NOT NULL ENABLE);
  ALTER TABLE ALLOC_RCVD_DIFF_QTY_ERROR_TMP MODIFY (ALLOC_ORDER_ID NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ALLOC_RCVD_DIFF_QTY_ERROR_TXN
--------------------------------------------------------

  ALTER TABLE ALLOC_RCVD_DIFF_QTY_ERROR_TXN MODIFY (RCVD_SKU_CNT NOT NULL ENABLE);
  ALTER TABLE ALLOC_RCVD_DIFF_QTY_ERROR_TXN MODIFY (RCVD_ORDER_ID NOT NULL ENABLE);
  ALTER TABLE ALLOC_RCVD_DIFF_QTY_ERROR_TXN MODIFY (ALLOC_SKU_CNT NOT NULL ENABLE);
  ALTER TABLE ALLOC_RCVD_DIFF_QTY_ERROR_TXN MODIFY (DELIVERY_DATE NOT NULL ENABLE);
  ALTER TABLE ALLOC_RCVD_DIFF_QTY_ERROR_TXN MODIFY (NAME NOT NULL ENABLE);
  ALTER TABLE ALLOC_RCVD_DIFF_QTY_ERROR_TXN MODIFY (PASS NOT NULL ENABLE);
  ALTER TABLE ALLOC_RCVD_DIFF_QTY_ERROR_TXN MODIFY (USERNAME NOT NULL ENABLE);
  ALTER TABLE ALLOC_RCVD_DIFF_QTY_ERROR_TXN MODIFY (SELLER_ID NOT NULL ENABLE);
  ALTER TABLE ALLOC_RCVD_DIFF_QTY_ERROR_TXN MODIFY (ALLOC_ORDER_ID NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EON_ADMIN_MEMBER
--------------------------------------------------------

  ALTER TABLE EON_ADMIN_MEMBER ADD CONSTRAINT EON_ADMIN_MEMBER_PK PRIMARY KEY (ADMIN_MEMBER_ID)
  USING INDEX TABLESPACE EON_INDX01;
  ALTER TABLE EON_ADMIN_MEMBER MODIFY (START_DATE NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EON_AKADEN_SKU
--------------------------------------------------------

  ALTER TABLE EON_AKADEN_SKU ADD CONSTRAINT EON_AKADEN_SKU_PK PRIMARY KEY (AKADEN_SKU_ID)
  USING INDEX TABLESPACE EON_INDX01;
  ALTER TABLE EON_AKADEN_SKU MODIFY (AKADEN_SKU_ID NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EON_AUDIT_TRAIL
--------------------------------------------------------

  ALTER TABLE EON_AUDIT_TRAIL MODIFY (DB_DATE NOT NULL ENABLE);
  ALTER TABLE EON_AUDIT_TRAIL MODIFY (SYSTEM_DATE NOT NULL ENABLE);
  ALTER TABLE EON_AUDIT_TRAIL MODIFY (URL_PATH NOT NULL ENABLE);
  ALTER TABLE EON_AUDIT_TRAIL MODIFY (LOG_TYPE NOT NULL ENABLE);
  ALTER TABLE EON_AUDIT_TRAIL MODIFY (PROCESS_ID NOT NULL ENABLE);
  ALTER TABLE EON_AUDIT_TRAIL MODIFY (USERNAME NOT NULL ENABLE);
  ALTER TABLE EON_AUDIT_TRAIL MODIFY (USER_ID NOT NULL ENABLE);
  ALTER TABLE EON_AUDIT_TRAIL MODIFY (ID NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EON_AUTODWNLD_SCHEDULE
--------------------------------------------------------

  ALTER TABLE EON_AUTODWNLD_SCHEDULE ADD CONSTRAINT EON_AUTODWNLD_SCHEDULE_PK PRIMARY KEY (ID_SCHEDULE_CSV)
  USING INDEX TABLESPACE EON_INDX01;
--------------------------------------------------------
--  Constraints for Table EON_CATEGORY
--------------------------------------------------------

  ALTER TABLE EON_CATEGORY ADD CONSTRAINT EON_SKU_CATEGORY_PK PRIMARY KEY (SKU_CATEGORY_ID)
  USING INDEX TABLESPACE EON_INDX01;
--------------------------------------------------------
--  Constraints for Table EON_COLUMN_WIDTH
--------------------------------------------------------

  ALTER TABLE EON_COLUMN_WIDTH MODIFY (WIDTH NOT NULL ENABLE);
  ALTER TABLE EON_COLUMN_WIDTH MODIFY (HEADER_KEY NOT NULL ENABLE);
  ALTER TABLE EON_COLUMN_WIDTH MODIFY (FK_USER_ID NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EON_COMMENTS_INBOX
--------------------------------------------------------

  ALTER TABLE EON_COMMENTS_INBOX ADD CONSTRAINT EON_COMMENTS_INBOX_PK PRIMARY KEY (COMMENTS_INBOX_ID)
  USING INDEX TABLESPACE EON_INDX01;
--------------------------------------------------------
--  Constraints for Table EON_COMMENTS_OUTBOX
--------------------------------------------------------

  ALTER TABLE EON_COMMENTS_OUTBOX ADD CONSTRAINT EON_COMMENTS_OUTBOX_PK PRIMARY KEY (COMMENTS_OUTBOX_ID)
  USING INDEX TABLESPACE EON_INDX01;
--------------------------------------------------------
--  Constraints for Table EON_COMPANY
--------------------------------------------------------

  ALTER TABLE EON_COMPANY ADD CONSTRAINT EON_COMPANY_PK PRIMARY KEY (COMPANY_ID)
  USING INDEX TABLESPACE EON_INDX01;
  ALTER TABLE EON_COMPANY ADD CONSTRAINT EON_COMPANY_UK2 UNIQUE (SHORT_NAME)
  USING INDEX TABLESPACE EON_INDX01;
  ALTER TABLE EON_COMPANY ADD CONSTRAINT EON_COMPANY_UK1 UNIQUE (COMPANY_NAME)
  USING INDEX TABLESPACE EON_INDX01;
  ALTER TABLE EON_COMPANY MODIFY (SOX_FLAG NOT NULL ENABLE);
  ALTER TABLE EON_COMPANY MODIFY (COMPANY_TYPE_ID NOT NULL ENABLE);
  ALTER TABLE EON_COMPANY MODIFY (SHORT_NAME NOT NULL ENABLE);
  ALTER TABLE EON_COMPANY MODIFY (COMPANY_NAME NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EON_COMPANY_DEALING_PATTERN
--------------------------------------------------------

  ALTER TABLE EON_COMPANY_DEALING_PATTERN ADD CONSTRAINT COMPANY_DEALING_PATTERN_UK1 UNIQUE (COMPANY_01, COMPANY_02, DEALING_PATTERN_RELATION_ID)
  USING INDEX TABLESPACE EON_INDX01;
  ALTER TABLE EON_COMPANY_DEALING_PATTERN ADD CONSTRAINT EON_COMPANY_DEALING_PATTERN_PK PRIMARY KEY (COMPANY_DEALING_PATTERN_ID)
  USING INDEX TABLESPACE EON_INDX01;
  ALTER TABLE EON_COMPANY_DEALING_PATTERN MODIFY (ISACTIVE NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EON_COMPANY_TYPE
--------------------------------------------------------

  ALTER TABLE EON_COMPANY_TYPE ADD CONSTRAINT EON_COMPANY_TYPE_PK PRIMARY KEY (COMPANY_TYPE_ID)
  USING INDEX TABLESPACE EON_INDX01;
--------------------------------------------------------
--  Constraints for Table EON_DEALING_PATTERN_RELATION
--------------------------------------------------------

  ALTER TABLE EON_DEALING_PATTERN_RELATION ADD CONSTRAINT EON_DEALING_PATTERNRELATION_PK PRIMARY KEY (DEALING_PATTERN_RELATION_ID)
  USING INDEX TABLESPACE EON_INDX01;
--------------------------------------------------------
--  Constraints for Table EON_EXCEL_SETTING
--------------------------------------------------------

  ALTER TABLE EON_EXCEL_SETTING ADD CONSTRAINT EON_EXCEL_SETTING_PK PRIMARY KEY (USER_ID)
  USING INDEX TABLESPACE EON_INDX01;
  ALTER TABLE EON_EXCEL_SETTING MODIFY (USER_ID NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EON_FORGOT_PASSWORD_LINK
--------------------------------------------------------

  ALTER TABLE EON_FORGOT_PASSWORD_LINK ADD CONSTRAINT EON_FORGOT_PASSWORD_LINK_PK PRIMARY KEY (FORGOT_PASSWORD_LINK_ID)
  USING INDEX TABLESPACE EON_INDX01;
--------------------------------------------------------
--  Constraints for Table EON_LOGIN_INQUIRY_REQUEST
--------------------------------------------------------

  ALTER TABLE EON_LOGIN_INQUIRY_REQUEST ADD CONSTRAINT EON_LOGIN_INQUIRY_REQUEST_PK PRIMARY KEY (INQUIRY_REQUEST_ID)
  USING INDEX TABLESPACE EON_INDX01;
--------------------------------------------------------
--  Constraints for Table EON_ORDER
--------------------------------------------------------

  ALTER TABLE EON_ORDER ADD CONSTRAINT EON_ORDER_UK1 UNIQUE (SELLER_ID, BUYER_ID, DELIVERY_DATE)
  USING INDEX TABLESPACE EON_INDX01;
  ALTER TABLE EON_ORDER ADD CONSTRAINT EON_ORDER_PK PRIMARY KEY (ORDER_ID)
  USING INDEX TABLESPACE EON_INDX01;
--------------------------------------------------------
--  Constraints for Table EON_ORDER_AKADEN
--------------------------------------------------------

  ALTER TABLE EON_ORDER_AKADEN ADD CONSTRAINT EON_ORDER_AKADEN_PK PRIMARY KEY (ORDER_AKADEN_ID)
  USING INDEX TABLESPACE EON_INDX01;
--------------------------------------------------------
--  Constraints for Table EON_ORDER_ALLOCATION
--------------------------------------------------------

  ALTER TABLE EON_ORDER_ALLOCATION ADD CONSTRAINT EON_ORDER_ALLOCATION_UK1 UNIQUE (ORDER_ID, SKU_ID)
  USING INDEX TABLESPACE EON_INDX01;
  ALTER TABLE EON_ORDER_ALLOCATION ADD CONSTRAINT EON_ORDER_ALLOCATION_PK PRIMARY KEY (ORDER_ALLOCATION_ID)
  USING INDEX TABLESPACE EON_INDX01;
--------------------------------------------------------
--  Constraints for Table EON_ORDER_BILLING
--------------------------------------------------------

  ALTER TABLE EON_ORDER_BILLING ADD CONSTRAINT EON_ORDER_BILLING_UK1 UNIQUE (ORDER_ID, SKU_ID)
  USING INDEX TABLESPACE EON_INDX01;
  ALTER TABLE EON_ORDER_BILLING ADD CONSTRAINT EON_ORDER_BILLING_PK PRIMARY KEY (ORDER_BILLING_ID)
  USING INDEX TABLESPACE EON_INDX01;
--------------------------------------------------------
--  Constraints for Table EON_ORDER_ITEM
--------------------------------------------------------

  ALTER TABLE EON_ORDER_ITEM ADD CONSTRAINT EON_ORDER_ITEM_UK1 UNIQUE (ORDER_ID, SKU_ID)
  USING INDEX TABLESPACE EON_INDX01;
  ALTER TABLE EON_ORDER_ITEM ADD CONSTRAINT EON_ORDER_ITEM_PK PRIMARY KEY (ORDER_ITEM_ID)
  USING INDEX TABLESPACE EON_INDX01;
  ALTER TABLE EON_ORDER_ITEM MODIFY (BAOS_VIS_FLAG NOT NULL ENABLE);
  ALTER TABLE EON_ORDER_ITEM MODIFY (SOS_VIS_FLAG NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EON_ORDER_RECEIVED
--------------------------------------------------------

  ALTER TABLE EON_ORDER_RECEIVED ADD CONSTRAINT EON_ORDER_RECEIVED_UK1 UNIQUE (ORDER_ID, SKU_ID)
  USING INDEX TABLESPACE EON_INDX01;
  ALTER TABLE EON_ORDER_RECEIVED ADD CONSTRAINT EON_ORDER_RECEIVED_PK PRIMARY KEY (ORDER_RECEIVED_ID)
  USING INDEX TABLESPACE EON_INDX01;
--------------------------------------------------------
--  Constraints for Table EON_ORDER_UNIT
--------------------------------------------------------

  ALTER TABLE EON_ORDER_UNIT ADD CONSTRAINT EON_ORDER_UNIT_PK PRIMARY KEY (ORDER_UNIT_ID)
  USING INDEX TABLESPACE EON_INDX01;
  ALTER TABLE EON_ORDER_UNIT MODIFY (ORDER_UNIT_NAME NOT NULL ENABLE);
  ALTER TABLE EON_ORDER_UNIT MODIFY (ORDER_UNIT_ID NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EON_PRODUCT_MASTER_FILE
--------------------------------------------------------

  ALTER TABLE EON_PRODUCT_MASTER_FILE ADD CONSTRAINT EON_PRODUCT_MASTER_FILE_PK PRIMARY KEY (PROD_MASTER_ID)
  USING INDEX TABLESPACE EON_INDX01;
--------------------------------------------------------
--  Constraints for Table EON_PRODUCT_MASTER_FILE_SKU
--------------------------------------------------------

  ALTER TABLE EON_PRODUCT_MASTER_FILE_SKU ADD CONSTRAINT EON_PRODUCT_MASTER_FILE_SKU_PK PRIMARY KEY (SKU_ID)
  USING INDEX TABLESPACE EON_INDX01;
--------------------------------------------------------
--  Constraints for Table EON_PROFIT_PREFERENCE
--------------------------------------------------------

  ALTER TABLE EON_PROFIT_PREFERENCE MODIFY (FK_ID_USER NOT NULL ENABLE);
  ALTER TABLE EON_PROFIT_PREFERENCE ADD CONSTRAINT EON_PROFIT_PREFERENCE_PK PRIMARY KEY (FK_ID_USER)
  USING INDEX TABLESPACE EON_INDX01;
--------------------------------------------------------
--  Constraints for Table EON_ROLES
--------------------------------------------------------

  ALTER TABLE EON_ROLES ADD CONSTRAINT EON_ROLES_PK PRIMARY KEY (ROLE_ID)
  USING INDEX TABLESPACE EON_INDX01;
--------------------------------------------------------
--  Constraints for Table EON_SELLING_UOM
--------------------------------------------------------

  ALTER TABLE EON_SELLING_UOM ADD CONSTRAINT EON_SELLING_UOM_PK PRIMARY KEY (ID_SELLING_UOM)
  USING INDEX TABLESPACE EON_INDX01;
  ALTER TABLE EON_SELLING_UOM MODIFY (ID_SELLING_UOM NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EON_SHEET_TYPE
--------------------------------------------------------

  ALTER TABLE EON_SHEET_TYPE ADD CONSTRAINT EON_SHEET_TYPE_PK PRIMARY KEY (SHEET_TYPE_ID)
  USING INDEX TABLESPACE EON_INDX01;
--------------------------------------------------------
--  Constraints for Table EON_SHOW_HIDE_COLUMN
--------------------------------------------------------

  ALTER TABLE EON_SHOW_HIDE_COLUMN ADD CONSTRAINT EON_SHOW_HIDE_COLUMN_PK PRIMARY KEY (USER_ID)
  USING INDEX TABLESPACE EON_INDX01;
  ALTER TABLE EON_SHOW_HIDE_COLUMN MODIFY (USER_ID NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EON_SKU
--------------------------------------------------------

  ALTER TABLE EON_SKU ADD CONSTRAINT EON_SKU_PK PRIMARY KEY (SKU_ID)
  USING INDEX TABLESPACE EON_INDX01;
  ALTER TABLE EON_SKU MODIFY (PACKAGE_QUANTITY NOT NULL ENABLE);
  ALTER TABLE EON_SKU MODIFY (SKU_NAME NOT NULL ENABLE);
  ALTER TABLE EON_SKU MODIFY (ORDER_UNIT_ID NOT NULL ENABLE);
  ALTER TABLE EON_SKU MODIFY (SKU_GROUP_ID NOT NULL ENABLE);
  ALTER TABLE EON_SKU MODIFY (SELLER_ID NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EON_SKU_BA
--------------------------------------------------------

  ALTER TABLE EON_SKU_BA ADD CONSTRAINT EON_SKU_BA_PK PRIMARY KEY (SKU_BA_ID)
  USING INDEX TABLESPACE EON_INDX01;
  ALTER TABLE EON_SKU_BA MODIFY (FK_SKU_ID NOT NULL ENABLE);
  ALTER TABLE EON_SKU_BA MODIFY (SKU_BA_ID NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EON_SKU_COLUMN
--------------------------------------------------------

  ALTER TABLE EON_SKU_COLUMN ADD CONSTRAINT EON_SKU_COLUMN_PK PRIMARY KEY (SKU_COLUMN_ID)
  USING INDEX TABLESPACE EON_INDX01;
--------------------------------------------------------
--  Constraints for Table EON_SKU_GROUP
--------------------------------------------------------

  ALTER TABLE EON_SKU_GROUP ADD CONSTRAINT EON_SKU_GROUP_PK PRIMARY KEY (SKU_GROUP_ID)
  USING INDEX TABLESPACE EON_INDX01;
--------------------------------------------------------
--  Constraints for Table EON_SORT_BUYERS
--------------------------------------------------------

  ALTER TABLE EON_SORT_BUYERS ADD CONSTRAINT EON_SORT_BUYERS_PK PRIMARY KEY (USER_ID, BUYER_ID)
  USING INDEX TABLESPACE EON_INDX01;
--------------------------------------------------------
--  Constraints for Table EON_SORT_COMPANY_BUYERS
--------------------------------------------------------

  ALTER TABLE EON_SORT_COMPANY_BUYERS ADD CONSTRAINT EON_SORT_COMPANY_BUYERS_PK PRIMARY KEY (USER_ID, COMPANY_ID)
  USING INDEX TABLESPACE EON_INDX01;
  ALTER TABLE EON_SORT_COMPANY_BUYERS MODIFY (USER_ID NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EON_SORT_COMPANY_SELLERS
--------------------------------------------------------

  ALTER TABLE EON_SORT_COMPANY_SELLERS ADD CONSTRAINT EON_SORT_COMPANY_SELLERS_PK PRIMARY KEY (USER_ID, COMPANY_ID)
  USING INDEX TABLESPACE USERS;
  ALTER TABLE EON_SORT_COMPANY_SELLERS MODIFY (USER_ID NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EON_SORT_SELLERS
--------------------------------------------------------

  ALTER TABLE EON_SORT_SELLERS ADD CONSTRAINT EON_SORT_SELLERS_PK PRIMARY KEY (USER_ID, SELLER_ID)
  USING INDEX TABLESPACE USERS;
--------------------------------------------------------
--  Constraints for Table EON_SORT_SKU
--------------------------------------------------------

  ALTER TABLE EON_SORT_SKU ADD CONSTRAINT EON_SORT_SKU_PK PRIMARY KEY (USER_ID)
  USING INDEX TABLESPACE EON_INDX01;
--------------------------------------------------------
--  Constraints for Table EON_SORT_SKU_GROUP
--------------------------------------------------------

  ALTER TABLE EON_SORT_SKU_GROUP ADD PRIMARY KEY (USER_ID, SKU_GROUP_ID)
  USING INDEX TABLESPACE EON_INDX01;

--------------------------------------------------------
--  Constraints for Table EON_USER_DEALING_PATTERN
--------------------------------------------------------

  ALTER TABLE EON_USER_DEALING_PATTERN ADD CONSTRAINT EON_USER_DEALING_PATTERN_PK PRIMARY KEY (USER_DEALING_PATTERN_ID)
  USING INDEX TABLESPACE EON_INDX01;
  ALTER TABLE EON_USER_DEALING_PATTERN MODIFY (START_DATE NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EON_USER_PREF_FLAGS
--------------------------------------------------------

  ALTER TABLE EON_USER_PREF_FLAGS ADD CONSTRAINT EON_USER_PREF_FLAGS_PK PRIMARY KEY (USER_PREF_ID)
  USING INDEX TABLESPACE EON_INDX01;
--------------------------------------------------------
--  Constraints for Table EON_USERS
--------------------------------------------------------

  ALTER TABLE EON_USERS ADD CONSTRAINT EON_USERS_UK1 UNIQUE (USERNAME)
  USING INDEX TABLESPACE EON_INDX01;
  ALTER TABLE EON_USERS ADD CONSTRAINT EON_USERS_PK PRIMARY KEY (USER_ID)
  USING INDEX TABLESPACE EON_INDX01;
  ALTER TABLE EON_USERS MODIFY (USE_BMS NOT NULL ENABLE);
  ALTER TABLE EON_USERS MODIFY (SHORTNAME NOT NULL ENABLE);
  ALTER TABLE EON_USERS MODIFY (NAME NOT NULL ENABLE);
  ALTER TABLE EON_USERS MODIFY (PASSWORD NOT NULL ENABLE);
  ALTER TABLE EON_USERS MODIFY (USERNAME NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EON_ZIP_CODE
--------------------------------------------------------

  ALTER TABLE EON_ZIP_CODE ADD CONSTRAINT EON_ZIP_CODE_PK PRIMARY KEY (ZIP_CODE)
  USING INDEX TABLESPACE EON_INDX01;
--------------------------------------------------------
--  Constraints for Table MIGRATION_DEALING_PATTERN
--------------------------------------------------------

  ALTER TABLE MIGRATION_DEALING_PATTERN ADD UNIQUE (USER1, USER2, RELATION)
  USING INDEX TABLESPACE EON_INDX01;
  ALTER TABLE MIGRATION_DEALING_PATTERN MODIFY (MIGRATION_STATUS NOT NULL ENABLE);
  ALTER TABLE MIGRATION_DEALING_PATTERN MODIFY (RELATION NOT NULL ENABLE);
  ALTER TABLE MIGRATION_DEALING_PATTERN MODIFY (USER2 NOT NULL ENABLE);
  ALTER TABLE MIGRATION_DEALING_PATTERN MODIFY (USER1 NOT NULL ENABLE);
  ALTER TABLE MIGRATION_DEALING_PATTERN MODIFY (BATCH_NUMBER NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MIGRATION_USER
--------------------------------------------------------

  ALTER TABLE MIGRATION_USER ADD UNIQUE (USERNAME)
  USING INDEX TABLESPACE EON_INDX01;
  ALTER TABLE MIGRATION_USER MODIFY (MIGRATION_STATUS NOT NULL ENABLE);
  ALTER TABLE MIGRATION_USER MODIFY (COMPANY_NAME NOT NULL ENABLE);
  ALTER TABLE MIGRATION_USER MODIFY (PASSWORD NOT NULL ENABLE);
  ALTER TABLE MIGRATION_USER MODIFY (USERNAME NOT NULL ENABLE);
  ALTER TABLE MIGRATION_USER MODIFY (BATCH_NUMBER NOT NULL ENABLE);

  --------------------------------------------------------
--  Ref Constraints for Table EON_ADMIN_MEMBER
--------------------------------------------------------

  ALTER TABLE EON_ADMIN_MEMBER ADD CONSTRAINT EON_ADMIN_MEMBER_FK1 FOREIGN KEY (ADMIN_ID)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_ADMIN_MEMBER ADD CONSTRAINT EON_ADMIN_MEMBER_FK2 FOREIGN KEY (MEMBER_ID)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_ADMIN_MEMBER ADD CONSTRAINT EON_ADMIN_MEMBER_FK3 FOREIGN KEY (DEALING_PATTERN_RELATION_ID)
      REFERENCES EON_DEALING_PATTERN_RELATION (DEALING_PATTERN_RELATION_ID) ENABLE;
  ALTER TABLE EON_ADMIN_MEMBER ADD CONSTRAINT EON_ADMIN_MEMBER_FK4 FOREIGN KEY (CREATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_ADMIN_MEMBER ADD CONSTRAINT EON_ADMIN_MEMBER_FK5 FOREIGN KEY (UPDATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EON_AKADEN_SKU
--------------------------------------------------------

  ALTER TABLE EON_AKADEN_SKU ADD CONSTRAINT EON_AKADEN_SKU_FK1 FOREIGN KEY (SKU_ID)
      REFERENCES EON_SKU (SKU_ID) ENABLE;
  ALTER TABLE EON_AKADEN_SKU ADD CONSTRAINT EON_AKADEN_SKU_FK2 FOREIGN KEY (SELLER_ID)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_AKADEN_SKU ADD CONSTRAINT EON_AKADEN_SKU_FK3 FOREIGN KEY (SKU_CATEGORY_ID)
      REFERENCES EON_CATEGORY (SKU_CATEGORY_ID) ENABLE;
  ALTER TABLE EON_AKADEN_SKU ADD CONSTRAINT EON_AKADEN_SKU_FK4 FOREIGN KEY (SKU_GROUP_ID)
      REFERENCES EON_SKU_GROUP (SKU_GROUP_ID) ENABLE;
  ALTER TABLE EON_AKADEN_SKU ADD CONSTRAINT EON_AKADEN_SKU_FK5 FOREIGN KEY (ORDER_UNIT_ID)
      REFERENCES EON_ORDER_UNIT (ORDER_UNIT_ID) ENABLE;
  ALTER TABLE EON_AKADEN_SKU ADD CONSTRAINT EON_AKADEN_SKU_FK6 FOREIGN KEY (PROPOSED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_AKADEN_SKU ADD CONSTRAINT EON_AKADEN_SKU_FK7 FOREIGN KEY (SHEET_TYPE_ID)
      REFERENCES EON_SHEET_TYPE (SHEET_TYPE_ID) ENABLE;
  ALTER TABLE EON_AKADEN_SKU ADD CONSTRAINT EON_AKADEN_SKU_FK8 FOREIGN KEY (CREATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_AKADEN_SKU ADD CONSTRAINT EON_AKADEN_SKU_FK9 FOREIGN KEY (UPDATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EON_AUTODWNLD_BUYERS
--------------------------------------------------------

  ALTER TABLE EON_AUTODWNLD_BUYERS ADD CONSTRAINT EON_AUTODWNLD_BUYERS_FK1 FOREIGN KEY (FK_ID_SCHEDULE_CSV)
      REFERENCES EON_AUTODWNLD_SCHEDULE (ID_SCHEDULE_CSV) ENABLE;
  ALTER TABLE EON_AUTODWNLD_BUYERS ADD CONSTRAINT EON_AUTODWNLD_BUYERS_FK2 FOREIGN KEY (FK_ID_BUYER)
      REFERENCES EON_USERS (USER_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EON_AUTODWNLD_EXCEPT_DATE
--------------------------------------------------------

  ALTER TABLE EON_AUTODWNLD_EXCEPT_DATE ADD CONSTRAINT EON_AUTODWNLD_EXCEPT_DATE_FK FOREIGN KEY (FK_ID_SCHEDULE_CSV)
      REFERENCES EON_AUTODWNLD_SCHEDULE (ID_SCHEDULE_CSV) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EON_AUTODWNLD_SCHEDULE
--------------------------------------------------------

  ALTER TABLE EON_AUTODWNLD_SCHEDULE ADD CONSTRAINT EON_AUTODWNLD_SCHEDULE_FK1 FOREIGN KEY (FK_ID_USER)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_AUTODWNLD_SCHEDULE ADD CONSTRAINT EON_AUTODWNLD_SCHEDULE_FK2 FOREIGN KEY (FK_ID_SHEET_TYPE)
      REFERENCES EON_SHEET_TYPE (SHEET_TYPE_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EON_AUTODWNLD_SELLERS
--------------------------------------------------------

  ALTER TABLE EON_AUTODWNLD_SELLERS ADD CONSTRAINT EON_AUTODWNLD_SELLERS_FK1 FOREIGN KEY (FK_ID_SCHEDULE_CSV)
      REFERENCES EON_AUTODWNLD_SCHEDULE (ID_SCHEDULE_CSV) ENABLE;
  ALTER TABLE EON_AUTODWNLD_SELLERS ADD CONSTRAINT EON_AUTODWNLD_SELLERS_FK2 FOREIGN KEY (FK_ID_SELLER)
      REFERENCES EON_USERS (USER_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EON_COLUMN_WIDTH
--------------------------------------------------------

  ALTER TABLE EON_COLUMN_WIDTH ADD CONSTRAINT EON_COLUMN_WIDTH_FK1 FOREIGN KEY (FK_USER_ID)
      REFERENCES EON_USERS (USER_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EON_COMMENTS_INBOX
--------------------------------------------------------

  ALTER TABLE EON_COMMENTS_INBOX ADD CONSTRAINT EON_COMMENTS_INBOX_FK1 FOREIGN KEY (SENDER_ENTITY_ID)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_COMMENTS_INBOX ADD CONSTRAINT EON_COMMENTS_INBOX_FK2 FOREIGN KEY (RECIPIENT_ENTITY_ID)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_COMMENTS_INBOX ADD CONSTRAINT EON_COMMENTS_INBOX_FK3 FOREIGN KEY (CREATE_USER_ID)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_COMMENTS_INBOX ADD CONSTRAINT EON_COMMENTS_INBOX_FK4 FOREIGN KEY (UPDATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EON_COMMENTS_OUTBOX
--------------------------------------------------------

  ALTER TABLE EON_COMMENTS_OUTBOX ADD CONSTRAINT EON_COMMENTS_OUTBOX_FK1 FOREIGN KEY (SENDER_ENTITY_ID)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_COMMENTS_OUTBOX ADD CONSTRAINT EON_COMMENTS_OUTBOX_FK2 FOREIGN KEY (CREATE_USER_ID)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_COMMENTS_OUTBOX ADD CONSTRAINT EON_COMMENTS_OUTBOX_FK3 FOREIGN KEY (UPDATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EON_COMPANY
--------------------------------------------------------

  ALTER TABLE EON_COMPANY ADD CONSTRAINT EON_COMPANY_FK1 FOREIGN KEY (CREATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_COMPANY ADD CONSTRAINT EON_COMPANY_FK2 FOREIGN KEY (UPDATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_COMPANY ADD CONSTRAINT EON_COMPANY_FK3 FOREIGN KEY (COMPANY_TYPE_ID)
      REFERENCES EON_COMPANY_TYPE (COMPANY_TYPE_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EON_COMPANY_DEALING_PATTERN
--------------------------------------------------------

  ALTER TABLE EON_COMPANY_DEALING_PATTERN ADD CONSTRAINT EON_COMPANYDEALINGPATTERN_FK1 FOREIGN KEY (COMPANY_01)
      REFERENCES EON_COMPANY (COMPANY_ID) ENABLE;
  ALTER TABLE EON_COMPANY_DEALING_PATTERN ADD CONSTRAINT EON_COMPANYDEALINGPATTERN_FK2 FOREIGN KEY (COMPANY_02)
      REFERENCES EON_COMPANY (COMPANY_ID) ENABLE;
  ALTER TABLE EON_COMPANY_DEALING_PATTERN ADD CONSTRAINT EON_COMPANYDEALINGPATTERN_FK3 FOREIGN KEY (DEALING_PATTERN_RELATION_ID)
      REFERENCES EON_DEALING_PATTERN_RELATION (DEALING_PATTERN_RELATION_ID) ENABLE;
  ALTER TABLE EON_COMPANY_DEALING_PATTERN ADD CONSTRAINT EON_COMPANYDEALINGPATTERN_FK4 FOREIGN KEY (CREATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_COMPANY_DEALING_PATTERN ADD CONSTRAINT EON_COMPANYDEALINGPATTERN_FK5 FOREIGN KEY (UPDATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EON_EXCEL_SETTING
--------------------------------------------------------

  ALTER TABLE EON_EXCEL_SETTING ADD CONSTRAINT EON_EXCEL_SETTING_FK1 FOREIGN KEY (USER_ID)
      REFERENCES EON_USERS (USER_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EON_FORGOT_PASSWORD_LINK
--------------------------------------------------------

  ALTER TABLE EON_FORGOT_PASSWORD_LINK ADD CONSTRAINT EON_FORGOT_PASSWORD_LINK_FK1 FOREIGN KEY (USER_ID)
      REFERENCES EON_USERS (USER_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EON_ORDER
--------------------------------------------------------

  ALTER TABLE EON_ORDER ADD CONSTRAINT EON_ORDER_FK1 FOREIGN KEY (BUYER_ID)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_ORDER ADD CONSTRAINT EON_ORDER_FK10 FOREIGN KEY (ALLOCATION_PUBLISHED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_ORDER ADD CONSTRAINT EON_ORDER_FK11 FOREIGN KEY (ALLOCATION_FINALIZED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_ORDER ADD CONSTRAINT EON_ORDER_FK12 FOREIGN KEY (ALLOCATION_UNFINALIZED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_ORDER ADD CONSTRAINT EON_ORDER_FK13 FOREIGN KEY (RECEIVED_APPROVED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_ORDER ADD CONSTRAINT EON_ORDER_FK14 FOREIGN KEY (RECEIVED_UNAPPROVED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_ORDER ADD CONSTRAINT EON_ORDER_FK15 FOREIGN KEY (RECEIVED_SAVED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_ORDER ADD CONSTRAINT EON_ORDER_FK16 FOREIGN KEY (BILLING_SAVED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_ORDER ADD CONSTRAINT EON_ORDER_FK17 FOREIGN KEY (BILLING_FINALIZED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_ORDER ADD CONSTRAINT EON_ORDER_FK18 FOREIGN KEY (BILLING_UNFINALIZED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_ORDER ADD CONSTRAINT EON_ORDER_FK19 FOREIGN KEY (AKADEN_SAVED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_ORDER ADD CONSTRAINT EON_ORDER_FK2 FOREIGN KEY (SELLER_ID)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_ORDER ADD CONSTRAINT EON_ORDER_FK20 FOREIGN KEY (ORDER_PUBLISHED_BY_BA)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_ORDER ADD CONSTRAINT EON_ORDER_FK21 FOREIGN KEY (CREATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_ORDER ADD CONSTRAINT EON_ORDER_FK22 FOREIGN KEY (UPDATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_ORDER ADD CONSTRAINT EON_ORDER_FK3 FOREIGN KEY (ORDER_SAVED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_ORDER ADD CONSTRAINT EON_ORDER_FK4 FOREIGN KEY (ORDER_PUBLISHED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_ORDER ADD CONSTRAINT EON_ORDER_FK5 FOREIGN KEY (ORDER_FINALIZED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_ORDER ADD CONSTRAINT EON_ORDER_FK6 FOREIGN KEY (ORDER_UNFINALIZED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_ORDER ADD CONSTRAINT EON_ORDER_FK7 FOREIGN KEY (ORDER_LOCKED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_ORDER ADD CONSTRAINT EON_ORDER_FK8 FOREIGN KEY (ORDER_UNLOCKED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_ORDER ADD CONSTRAINT EON_ORDER_FK9 FOREIGN KEY (ALLOCATION_SAVED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EON_ORDER_AKADEN
--------------------------------------------------------

  ALTER TABLE EON_ORDER_AKADEN ADD CONSTRAINT EON_ORDER_AKADEN_FK1 FOREIGN KEY (AKADEN_SKU_ID)
      REFERENCES EON_AKADEN_SKU (AKADEN_SKU_ID) ENABLE;
  ALTER TABLE EON_ORDER_AKADEN ADD CONSTRAINT EON_ORDER_AKADEN_FK2 FOREIGN KEY (ORDER_ID)
      REFERENCES EON_ORDER (ORDER_ID) ENABLE;
  ALTER TABLE EON_ORDER_AKADEN ADD CONSTRAINT EON_ORDER_AKADEN_FK3 FOREIGN KEY (CREATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_ORDER_AKADEN ADD CONSTRAINT EON_ORDER_AKADEN_FK4 FOREIGN KEY (UPDATE_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EON_ORDER_ALLOCATION
--------------------------------------------------------

  ALTER TABLE EON_ORDER_ALLOCATION ADD CONSTRAINT EON_ORDER_ALLOCATION_FK1 FOREIGN KEY (ORDER_ID)
      REFERENCES EON_ORDER (ORDER_ID) ENABLE;
  ALTER TABLE EON_ORDER_ALLOCATION ADD CONSTRAINT EON_ORDER_ALLOCATION_FK2 FOREIGN KEY (SKU_ID)
      REFERENCES EON_SKU (SKU_ID) ENABLE;
  ALTER TABLE EON_ORDER_ALLOCATION ADD CONSTRAINT EON_ORDER_ALLOCATION_FK3 FOREIGN KEY (CREATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_ORDER_ALLOCATION ADD CONSTRAINT EON_ORDER_ALLOCATION_FK4 FOREIGN KEY (UPDATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_ORDER_ALLOCATION ADD CONSTRAINT EON_ORDER_ALLOCATION_FK5 FOREIGN KEY (SKU_BA_ID)
      REFERENCES EON_SKU_BA (SKU_BA_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EON_ORDER_BILLING
--------------------------------------------------------

  ALTER TABLE EON_ORDER_BILLING ADD CONSTRAINT EON_ORDER_BILLING_FK1 FOREIGN KEY (ORDER_ID)
      REFERENCES EON_ORDER (ORDER_ID) ENABLE;
  ALTER TABLE EON_ORDER_BILLING ADD CONSTRAINT EON_ORDER_BILLING_FK2 FOREIGN KEY (SKU_ID)
      REFERENCES EON_SKU (SKU_ID) ENABLE;
  ALTER TABLE EON_ORDER_BILLING ADD CONSTRAINT EON_ORDER_BILLING_FK3 FOREIGN KEY (CREATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_ORDER_BILLING ADD CONSTRAINT EON_ORDER_BILLING_FK4 FOREIGN KEY (UPDATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_ORDER_BILLING ADD CONSTRAINT EON_ORDER_BILLING_FK5 FOREIGN KEY (SKU_BA_ID)
      REFERENCES EON_SKU_BA (SKU_BA_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EON_ORDER_ITEM
--------------------------------------------------------

  ALTER TABLE EON_ORDER_ITEM ADD CONSTRAINT EON_ORDER_ITEM_FK1 FOREIGN KEY (ORDER_ID)
      REFERENCES EON_ORDER (ORDER_ID) ENABLE;
  ALTER TABLE EON_ORDER_ITEM ADD CONSTRAINT EON_ORDER_ITEM_FK2 FOREIGN KEY (SKU_ID)
      REFERENCES EON_SKU (SKU_ID) ENABLE;
  ALTER TABLE EON_ORDER_ITEM ADD CONSTRAINT EON_ORDER_ITEM_FK3 FOREIGN KEY (CREATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_ORDER_ITEM ADD CONSTRAINT EON_ORDER_ITEM_FK4 FOREIGN KEY (UPDATE_BY_USERS_ID)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_ORDER_ITEM ADD CONSTRAINT EON_ORDER_ITEM_FK5 FOREIGN KEY (SKU_BA_ID)
      REFERENCES EON_SKU_BA (SKU_BA_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EON_ORDER_RECEIVED
--------------------------------------------------------

  ALTER TABLE EON_ORDER_RECEIVED ADD CONSTRAINT EON_ORDER_RECEIVED_FK1 FOREIGN KEY (ORDER_ID)
      REFERENCES EON_ORDER (ORDER_ID) ENABLE;
  ALTER TABLE EON_ORDER_RECEIVED ADD CONSTRAINT EON_ORDER_RECEIVED_FK2 FOREIGN KEY (SKU_ID)
      REFERENCES EON_SKU (SKU_ID) ENABLE;
  ALTER TABLE EON_ORDER_RECEIVED ADD CONSTRAINT EON_ORDER_RECEIVED_FK3 FOREIGN KEY (CREATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_ORDER_RECEIVED ADD CONSTRAINT EON_ORDER_RECEIVED_FK4 FOREIGN KEY (UPDATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_ORDER_RECEIVED ADD CONSTRAINT EON_ORDER_RECEIVED_FK5 FOREIGN KEY (SKU_BA_ID)
      REFERENCES EON_SKU_BA (SKU_BA_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EON_ORDER_UNIT
--------------------------------------------------------

  ALTER TABLE EON_ORDER_UNIT ADD CONSTRAINT EON_ORDER_UNIT_FK1 FOREIGN KEY (CATEGORY_ID)
      REFERENCES EON_CATEGORY (SKU_CATEGORY_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EON_PRODUCT_MASTER_FILE
--------------------------------------------------------

  ALTER TABLE EON_PRODUCT_MASTER_FILE ADD CONSTRAINT EON_PRODUCT_MASTER_FILE_FK1 FOREIGN KEY (USER_ID)
      REFERENCES EON_USERS (USER_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EON_PRODUCT_MASTER_FILE_SKU
--------------------------------------------------------

  ALTER TABLE EON_PRODUCT_MASTER_FILE_SKU ADD CONSTRAINT EON_PRODUCT_MASTER_FILESKU_FK2 FOREIGN KEY (PROD_MASTER_ID)
      REFERENCES EON_PRODUCT_MASTER_FILE (PROD_MASTER_ID) ENABLE;
  ALTER TABLE EON_PRODUCT_MASTER_FILE_SKU ADD CONSTRAINT EON_PRODUCT_MASTER_FILESKU_FK3 FOREIGN KEY (SELLER_ID)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_PRODUCT_MASTER_FILE_SKU ADD CONSTRAINT EON_PRODUCT_MASTER_FILESKU_FK4 FOREIGN KEY (SKU_CATEGORY_ID)
      REFERENCES EON_CATEGORY (SKU_CATEGORY_ID) ENABLE;
  ALTER TABLE EON_PRODUCT_MASTER_FILE_SKU ADD CONSTRAINT EON_PRODUCT_MASTER_FILESKU_FK5 FOREIGN KEY (SKU_GROUP_ID)
      REFERENCES EON_SKU_GROUP (SKU_GROUP_ID) ENABLE;
  ALTER TABLE EON_PRODUCT_MASTER_FILE_SKU ADD CONSTRAINT EON_PRODUCT_MASTER_FILESKU_FK6 FOREIGN KEY (ORDER_UNIT_ID)
      REFERENCES EON_ORDER_UNIT (ORDER_UNIT_ID) ENABLE;
  ALTER TABLE EON_PRODUCT_MASTER_FILE_SKU ADD CONSTRAINT EON_PRODUCT_MASTER_FILESKU_FK7 FOREIGN KEY (CREATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_PRODUCT_MASTER_FILE_SKU ADD CONSTRAINT EON_PRODUCT_MASTER_FILESKU_FK8 FOREIGN KEY (UPDATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EON_PROFIT_PREFERENCE
--------------------------------------------------------

  ALTER TABLE EON_PROFIT_PREFERENCE ADD CONSTRAINT EON_PROFIT_PREFERENCE_FK1 FOREIGN KEY (FK_ID_USER)
      REFERENCES EON_USERS (USER_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EON_SHEET_TYPE
--------------------------------------------------------

  ALTER TABLE EON_SHEET_TYPE ADD CONSTRAINT EON_SHEET_TYPE_FK1 FOREIGN KEY (ROLE_ID)
      REFERENCES EON_ROLES (ROLE_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EON_SKU
--------------------------------------------------------

  ALTER TABLE EON_SKU ADD CONSTRAINT EON_SKU_FK1 FOREIGN KEY (SHEET_TYPE_ID)
      REFERENCES EON_SHEET_TYPE (SHEET_TYPE_ID) ENABLE;
  ALTER TABLE EON_SKU ADD CONSTRAINT EON_SKU_FK2 FOREIGN KEY (SKU_CATEGORY_ID)
      REFERENCES EON_CATEGORY (SKU_CATEGORY_ID) ENABLE;
  ALTER TABLE EON_SKU ADD CONSTRAINT EON_SKU_FK3 FOREIGN KEY (SELLER_ID)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_SKU ADD CONSTRAINT EON_SKU_FK4 FOREIGN KEY (ORIGINAL_SKU_ID)
      REFERENCES EON_SKU (SKU_ID) ENABLE;
  ALTER TABLE EON_SKU ADD CONSTRAINT EON_SKU_FK5 FOREIGN KEY (PROPOSED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_SKU ADD CONSTRAINT EON_SKU_FK6 FOREIGN KEY (SKU_GROUP_ID)
      REFERENCES EON_SKU_GROUP (SKU_GROUP_ID) ENABLE;
  ALTER TABLE EON_SKU ADD CONSTRAINT EON_SKU_FK7 FOREIGN KEY (ORDER_UNIT_ID)
      REFERENCES EON_ORDER_UNIT (ORDER_UNIT_ID) ENABLE;
  ALTER TABLE EON_SKU ADD CONSTRAINT EON_SKU_FK8 FOREIGN KEY (CREATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_SKU ADD CONSTRAINT EON_SKU_FK9 FOREIGN KEY (UPDATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EON_SKU_BA
--------------------------------------------------------

  ALTER TABLE EON_SKU_BA ADD CONSTRAINT EON_SKU_BA_FK1 FOREIGN KEY (FK_SKU_ID)
      REFERENCES EON_SKU (SKU_ID) ENABLE;
  ALTER TABLE EON_SKU_BA ADD CONSTRAINT EON_SKU_BA_FK2 FOREIGN KEY (FK_ID_SELLING_UOM)
      REFERENCES EON_SELLING_UOM (ID_SELLING_UOM) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EON_SKU_GROUP
--------------------------------------------------------

  ALTER TABLE EON_SKU_GROUP ADD CONSTRAINT EON_SKU_GROUP_FK1 FOREIGN KEY (SKU_CATEGORY_ID)
      REFERENCES EON_CATEGORY (SKU_CATEGORY_ID) ENABLE;
  ALTER TABLE EON_SKU_GROUP ADD CONSTRAINT EON_SKU_GROUP_FK2 FOREIGN KEY (SELLER_ID)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_SKU_GROUP ADD CONSTRAINT EON_SKU_GROUP_FK3 FOREIGN KEY (ORIG_SKU_GROUP_ID)
      REFERENCES EON_SKU_GROUP (SKU_GROUP_ID) ENABLE;
  ALTER TABLE EON_SKU_GROUP ADD CONSTRAINT EON_SKU_GROUP_FK4 FOREIGN KEY (CREATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_SKU_GROUP ADD CONSTRAINT EON_SKU_GROUP_FK5 FOREIGN KEY (UPDATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EON_SORT_BUYERS
--------------------------------------------------------

  ALTER TABLE EON_SORT_BUYERS ADD CONSTRAINT EON_SORT_BUYERS_FK1 FOREIGN KEY (USER_ID)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_SORT_BUYERS ADD CONSTRAINT EON_SORT_BUYERS_FK2 FOREIGN KEY (BUYER_ID)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_SORT_BUYERS ADD CONSTRAINT EON_SORT_BUYERS_FK3 FOREIGN KEY (CREATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_SORT_BUYERS ADD CONSTRAINT EON_SORT_BUYERS_FK4 FOREIGN KEY (UPDATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EON_SORT_COMPANY_BUYERS
--------------------------------------------------------

  ALTER TABLE EON_SORT_COMPANY_BUYERS ADD CONSTRAINT EON_SORT_COMPANY_BUYERS_FK1 FOREIGN KEY (USER_ID)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_SORT_COMPANY_BUYERS ADD CONSTRAINT EON_SORT_COMPANY_BUYERS_FK2 FOREIGN KEY (COMPANY_ID)
      REFERENCES EON_COMPANY (COMPANY_ID) ENABLE;
  ALTER TABLE EON_SORT_COMPANY_BUYERS ADD CONSTRAINT EON_SORT_COMPANY_BUYERS_FK3 FOREIGN KEY (CREATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_SORT_COMPANY_BUYERS ADD CONSTRAINT EON_SORT_COMPANY_BUYERS_FK4 FOREIGN KEY (UPDATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EON_SORT_COMPANY_SELLERS
--------------------------------------------------------

  ALTER TABLE EON_SORT_COMPANY_SELLERS ADD CONSTRAINT EON_SORT_COMPANY_SELLERS_FK1 FOREIGN KEY (USER_ID)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_SORT_COMPANY_SELLERS ADD CONSTRAINT EON_SORT_COMPANY_SELLERS_FK2 FOREIGN KEY (COMPANY_ID)
      REFERENCES EON_COMPANY (COMPANY_ID) ENABLE;
  ALTER TABLE EON_SORT_COMPANY_SELLERS ADD CONSTRAINT EON_SORT_COMPANY_SELLERS_FK3 FOREIGN KEY (CREATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_SORT_COMPANY_SELLERS ADD CONSTRAINT EON_SORT_COMPANY_SELLERS_FK4 FOREIGN KEY (UPDATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EON_SORT_SELLERS
--------------------------------------------------------

  ALTER TABLE EON_SORT_SELLERS ADD CONSTRAINT EON_SORT_SELLERS_FK1 FOREIGN KEY (USER_ID)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_SORT_SELLERS ADD CONSTRAINT EON_SORT_SELLERS_FK2 FOREIGN KEY (SELLER_ID)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_SORT_SELLERS ADD CONSTRAINT EON_SORT_SELLERS_FK3 FOREIGN KEY (CREATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_SORT_SELLERS ADD CONSTRAINT EON_SORT_SELLERS_FK4 FOREIGN KEY (UPDATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EON_SORT_SKU
--------------------------------------------------------

  ALTER TABLE EON_SORT_SKU ADD CONSTRAINT EON_SORT_SKU_FK1 FOREIGN KEY (USER_ID)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_SORT_SKU ADD CONSTRAINT EON_SORT_SKU_FK2 FOREIGN KEY (CREATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_SORT_SKU ADD CONSTRAINT EON_SORT_SKU_FK3 FOREIGN KEY (UPDATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EON_SORT_SKU_GROUP
--------------------------------------------------------

  ALTER TABLE EON_SORT_SKU_GROUP ADD CONSTRAINT EON_SORT_SKU_GROUP_FK1 FOREIGN KEY (USER_ID)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_SORT_SKU_GROUP ADD CONSTRAINT EON_SORT_SKU_GROUP_FK2 FOREIGN KEY (SKU_CATEGORY_ID)
      REFERENCES EON_CATEGORY (SKU_CATEGORY_ID) ENABLE;
  ALTER TABLE EON_SORT_SKU_GROUP ADD CONSTRAINT EON_SORT_SKU_GROUP_FK3 FOREIGN KEY (SKU_GROUP_ID)
      REFERENCES EON_SKU_GROUP (SKU_GROUP_ID) ENABLE;
  ALTER TABLE EON_SORT_SKU_GROUP ADD CONSTRAINT EON_SORT_SKU_GROUP_FK4 FOREIGN KEY (CREATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_SORT_SKU_GROUP ADD CONSTRAINT EON_SORT_SKU_GROUP_FK5 FOREIGN KEY (UPDATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table EON_USER_DEALING_PATTERN
--------------------------------------------------------

  ALTER TABLE EON_USER_DEALING_PATTERN ADD CONSTRAINT EON_USER_DEALING_PATTERN_FK1 FOREIGN KEY (COMPANY_DEALING_PATTERN_ID)
      REFERENCES EON_COMPANY_DEALING_PATTERN (COMPANY_DEALING_PATTERN_ID) ENABLE;
  ALTER TABLE EON_USER_DEALING_PATTERN ADD CONSTRAINT EON_USER_DEALING_PATTERN_FK2 FOREIGN KEY (DEALING_PATTERN_RELATION_ID)
      REFERENCES EON_DEALING_PATTERN_RELATION (DEALING_PATTERN_RELATION_ID) ENABLE;
  ALTER TABLE EON_USER_DEALING_PATTERN ADD CONSTRAINT EON_USER_DEALING_PATTERN_FK3 FOREIGN KEY (USER_01)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_USER_DEALING_PATTERN ADD CONSTRAINT EON_USER_DEALING_PATTERN_FK4 FOREIGN KEY (USER_02)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_USER_DEALING_PATTERN ADD CONSTRAINT EON_USER_DEALING_PATTERN_FK5 FOREIGN KEY (CREATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_USER_DEALING_PATTERN ADD CONSTRAINT EON_USER_DEALING_PATTERN_FK6 FOREIGN KEY (UPDATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EON_USER_PREF_FLAGS
--------------------------------------------------------

  ALTER TABLE EON_USER_PREF_FLAGS ADD CONSTRAINT EON_USER_PREF_FLAGS_FK1 FOREIGN KEY (USER_ID)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_USER_PREF_FLAGS ADD CONSTRAINT EON_USER_PREF_FLAGS_FK2 FOREIGN KEY (CREATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_USER_PREF_FLAGS ADD CONSTRAINT EON_USER_PREF_FLAGS_FK3 FOREIGN KEY (UPDATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EON_USERS
--------------------------------------------------------

  ALTER TABLE EON_USERS ADD CONSTRAINT EON_USERS_FK1 FOREIGN KEY (COMPANY_ID)
      REFERENCES EON_COMPANY (COMPANY_ID) ENABLE;
  ALTER TABLE EON_USERS ADD CONSTRAINT EON_USERS_FK2 FOREIGN KEY (ROLE_ID)
      REFERENCES EON_ROLES (ROLE_ID) ENABLE;
  ALTER TABLE EON_USERS ADD CONSTRAINT EON_USERS_FK3 FOREIGN KEY (CREATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_USERS ADD CONSTRAINT EON_USERS_FK4 FOREIGN KEY (UPDATED_BY)
      REFERENCES EON_USERS (USER_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EON_USERS_CATEGORY
--------------------------------------------------------

  ALTER TABLE EON_USERS_CATEGORY ADD CONSTRAINT EON_USERS_CATEGORY_FK1 FOREIGN KEY (USER_ID)
      REFERENCES EON_USERS (USER_ID) ENABLE;
  ALTER TABLE EON_USERS_CATEGORY ADD CONSTRAINT EON_USERS_CATEGORY_FK2 FOREIGN KEY (CATEGORY_ID)
      REFERENCES EON_CATEGORY (SKU_CATEGORY_ID) ENABLE;
