
Insert into EON_DEALING_PATTERN_RELATION (DEALING_PATTERN_RELATION_ID,DESCRIPTION) values (10000,'SELLER-BUYER');
Insert into EON_DEALING_PATTERN_RELATION (DEALING_PATTERN_RELATION_ID,DESCRIPTION) values (10002,'BUYERADMIN-BUYER');
Insert into EON_DEALING_PATTERN_RELATION (DEALING_PATTERN_RELATION_ID,DESCRIPTION) values (10003,'SELLERADMIN-SELLER');
Insert into EON_DEALING_PATTERN_RELATION (DEALING_PATTERN_RELATION_ID,DESCRIPTION) values (10004,'CHOUAI-SELLER');
